### PR TITLE
SSP Data Definitions

### PR DESCRIPTION
**Pull request by bmaclach**
This PR updates the remaining DDs for SSP to match manual, including adding arcsin, arccos, and arctan to `Expr`.

### CODE REVIEW

**Comment by JacquesCarette** [comment]
And master needs merged because of conflicts.

**Comment by bmaclach** [comment]
@JacquesCarette The reason for the "non-implemented" parts is because I am going to implement them in my GOOL fork, and I don't see them as being urgently needed here right now, so I didn't want to bother doing them here only for them to be changed when GOOL gets merged in.

With regards to doing two pull requests in the same branch, as far as I'm aware, any commits added to a branch after opening a PR for that branch will just get added to the original PR, unless that PR has already been closed/merged. So I would have to wait for one PR to get merged before starting the next, even if I were to continue working on the same branch.

**Comment by JacquesCarette** [comment]
Ok (about non-implemented and 2 PRs).

**Comment by JacquesCarette** [comment]
And now there's even more conflicts...

**Comment by bmaclach** [comment]
Should be good to go now, if Travis passes!

**Pull request merged**
