### PR TITLE
Add more logging to `analysis` Makefile target

### PR DESCRIPTION
**Pull request by balacij**
Related to #2789 

It looks like much of the time in the `analysis` step is spent converting dot graphs into svgs and circo svgs.

### CODE REVIEW

**Review by JacquesCarette — APPROVED** [review]

**Comment by JacquesCarette** [comment]
So it would be good to know the relative time between `dot` and `circo`.

**Comment by balacij** [comment]
As part of the regular CI or as an option in the Makefile? Or did you mean in general?

**Comment by JacquesCarette** [comment]
I meant in general. Maybe one of `dot` and `circo` is just really slow, but the other is fast.

**Comment by balacij** [comment]
Ah, ok. The total time spent on conversion of the `dot`s is less than 4s, while the `circo` ones together take > 2min. `circo` hangs on the typegraph generation for entry "drasil" (>1min spent here) and for "gool" (~1min spent here).

**Comment by JacquesCarette** [comment]
I think we should drop `circo` entirely. I just looked at the results, and they were really not useful.

**Pull request merged**
