### PR TITLE
Modified self-referential GlassBR DDs to fix generated code

### PR DESCRIPTION
**Pull request by bmaclach**
This PR makes the changes discussed in #1135. Self-referential DDs in GlassBR no longer refer to themselves, instead referring to the correct interpolation function. This fixes the Calculations module of the generated code, though it results in some incorrect equations and descriptions in the SRS (issue about this coming soon).

### CODE REVIEW

**Comment by JacquesCarette** [comment]
Considering the breakage, should this PR be closed until a better solution is found?

**Comment by bmaclach** [comment]
@JacquesCarette I think the answer to that question depends on your input on #1139.

**Comment by JacquesCarette** [comment]
Agreed - see my comments there.

**Comment by bmaclach** [comment]
Implemented a hack as discussed in #1139 that allows symbols for implementation-stage functions to be used in the SRS. LaTeX and code should now both compile!

**Pull request merged**
