### PR TITLE
Updated Referencing in IMs

### PR DESCRIPTION
**Pull request by samm82**
As per #947, the Source field is now improved for IMs (the relevant example was GamePhysics).

### CODE REVIEW

**Comment by samm82** [comment]
Should the presence of a `Derivation` be enforced as well @JacquesCarette? Or should that be something we tackle later?

**Comment by JacquesCarette** [comment]
Later.

**Comment by samm82** [comment]
So this is ready to go then.

**Comment by JacquesCarette** [comment]
Waiting for Travis to complete.  Though @Mornix why is drasil-bot removing labels added by humans?

**Comment by Mornix** [comment]
That’s part of what `bot_enhancements` will address. It’s a bug with the shell version.

**Comment by Mornix** [comment]
s/will address/addresses/
(Mobile doesn’t let me edit my comments.)

**Pull request merged**
