### PR TITLE
Added drasil-database Subpackage

### PR DESCRIPTION
**Pull request by samm82**
As per #1294, the `drasil-subpackage` was created with the following modules moved to it from `drasil-lang`:

- `Language.Drasil.ChunkDB`
- `Language.Drasil.ChunkDB.GetChunk`
- `Language.Drasil.SystemInformation`

@JacquesCarette `make` runs fine with no differences, so everything "works" - I'm just not sure if I've matched the design you had in mind.

The main things that come to mind:
- Should `Database.Drasil` re-export everything like `Language.Drasil`?
- I had to add some imports to `Language.Drasil` for use in `Database.Drasil`. Are these hacks/should they be moved to the development package?

### CODE REVIEW

**Comment by JacquesCarette** [comment]
`Database.Drasil` should export only those things that are needed externally. `Language.Drasil` was overly generous there. Now's a good time to clean up.

The few exports you added seem harmless enough. We can revisit later.

**Comment by JacquesCarette** [comment]
So I'm going to wait just a little to merge this in, as it may cause other things to fail. But it is ready.

**Comment by JacquesCarette** [comment]
And I was just about to, but now there's a conflict in the way...

**Comment by samm82** [comment]
@JacquesCarette Fixed!

**Pull request merged**
