### PR TITLE
Moved GenDefn to drasil-theory

### PR DESCRIPTION
**Pull request by samm82**
As per #918, the `drasil-theory` package was created, and `GenDefn` was moved there.

@JacquesCarette - The `gd''` constructor (with the following type signature) is never used.
```haskell
gd'' :: RelationConcept -> [Reference] -> String -> [Sentence] -> GenDefn
```
1) Should it be removed?
2) Should the only other constructor `gd'` be renamed to `gd`?

If not, this PR can be merged.

### CODE REVIEW

**Comment by JacquesCarette** [comment]
Yes, please remove `gd''` and rename `gd'` to `gd`. May as well clean that up before merging.

**Comment by samm82** [comment]
@JacquesCarette I fixed both `gd` and the README, so this should be good to go.

**Comment by JacquesCarette** [comment]
Should I delete the branch, or will you continue to build on it?

**Comment by samm82** [comment]
I'll just make a new one for each move for simplicity

**Pull request merged**
