### PR TITLE
PR - Changing HTML indent size from 0 to 2 spaces

### PR DESCRIPTION
**Pull request by danscime**
Addresses #1512.

My process was changing the number used to create spaces from 0 to 2 in my first commit.
Then I changed the makefile to ignore whitespaces, so the only changes to be made were to fix line breaks.

Once make ran without error, I removed my previous addition to the makefile.
Now, the only diffs would be due to whitespace. So I replaced each file in stable with the build files (after doing brief scans for correctness.)

It would have been infeasible to do all of the indents manually, so I think this is probably the best way I could have done it.

### CODE REVIEW

**Comment by JacquesCarette** [comment]
Don't know why Travis doesn't seem to be terminating. In any case, merge needs to happen.

**Comment by Mornix** [comment]
Travis finished (successfully) but it appears to have not relayed that information to GitHub.

**Comment by JacquesCarette** [comment]
and of course, since I merged something else in, this now need yet another master merge.

**Comment by danscime** [comment]
Fixed

**Comment by JacquesCarette** [comment]
And, of course, I merged some things that were submitted earlier, so another merge is needed... But if you hurry, yours is likely to sneak in next!

**Comment by danscime** [comment]
Fixed.

**Pull request merged**
