### PR TITLE
Gamephy impulse

### PR DESCRIPTION
**Pull request by oluowoj**
Impulse derivation added to ImpulseV data definition.

drasil-example/Drasil/GamePhysics/DataDefs.hs
drasil-example/Drasil/GamePhysics/Unitals.hs

### CODE REVIEW

**Comment by oluowoj** [comment]
> Impulse derivation added to ImpulseV data definition.
> drasil-example/Drasil/GamePhysics/DataDefs.hs
> drasil-example/Drasil/GamePhysics/Unitals.hs
 @JacquesCarette does this pull request look okay to you? I see some other work in this pull request like the Research Grant PR, not sure what I am doing wrong.

**Comment by JacquesCarette** [comment]
It seems like maybe you start all your branches by starting from not-a-fresh-master ?  How did you create `gamephy_Impulse`?  Usually you do
```
git checkout master
git pull
git checkout -b gamephy_Impulse
```

**Comment by JacquesCarette** [comment]
Also the build is failing because you have  `hlint` warnings and some compile warnings too -- see https://travis-ci.org/JacquesCarette/Drasil/builds/534898290?utm_source=github_status&utm_medium=notification for details.

**Comment by JacquesCarette** [comment]
And somehow because of how you created this, there is "extra junk" in this PR that shouldn't be there. There seems to be something about how you're using git that isn't quite 'right'.

**Comment by oluowoj** [comment]
> It seems like maybe you start all your branches by starting from not-a-fresh-master ?  How did you create gamephy_Impulse?  Usually you do
> git checkout master
> git pull
> git checkout -b gamephy_Impulse

Yes I think you are right. I don't think I created these 2 from a "fresh master". I have noted this for subsequent branches

**Comment by smiths** [comment]
@oluowoj this advice from @JacquesCarette seems really useful for new developers.  Can you please add it to our Contributor's Guide.  If you worry that you won't remember to do this, please go ahead and create an issue for this task.

**Comment by oluowoj** [comment]
> @oluowoj this advice from @JacquesCarette seems really useful for new developers.  Can you please add it to our Contributor's Guide.  If you worry that you won't remember to do this, please go ahead and create an issue for this task.

I created an issue  #1379 so I don't miss it.

**Comment by JacquesCarette** [comment]
@smiths I was hoping you'd do a content review of this before its gets merged in. @oluowoj another merge is indeed.

**Comment by smiths** [comment]
Yes, @JacquesCarette, I can do a review, but it will have to wait until after tomorrow (May 28), since I'll be busy with the SE4Science workshop.  @oluowoj, please go ahead and fix the conflicting file.

**Comment by oluowoj** [comment]
sure

**Comment by JacquesCarette** [comment]
Should this PR also be closed?

**Comment by oluowoj** [comment]
Closing PR. it has been replaced by PR #1447

**Pull request closed without merging**
