### PR TITLE
Update type for representing named arguments from string to CodeChunk

### PR DESCRIPTION
**Pull request by bmaclach**
Small PR to improve `ExternalLibrary` by updating the type for representing the name of a named argument from string to a `CodeChunk` corresponding to the parameter-variable being referenced by name. This will make it easier to map to GOOL code for generating named parameters, and is less fragile than using strings.

#2019 and #2021 should be merged first. The only (non-merge) new commit is b7abee2.

### CODE REVIEW

**Comment by JacquesCarette** [comment]
There are now conflicts - can you resolve please?  Otherwise, this looks good.

**Comment by bmaclach** [comment]
Weirdly the merge succeeded without conflicts.

Anyway, merge is pushed but just a reminder that merging this will also implicitly merge #2019, so probably still want to hold off.

**Comment by JacquesCarette** [comment]
Weird. And indeed, I will hold off.

**Comment by bmaclach** [comment]
Again, the merges are resolving automatically locally even though GitHub is reporting conflicts...

**Pull request merged**
