### PR TITLE
Partial: 2287 GitHub actions: Build logs

### PR DESCRIPTION
**Pull request by balacij**
This is a PR for a part of the ticket, it creates builds with each commit (which we can disable whenever we want) and with each PR targeting master (so we can have PR tests -- which may not yet show in this PR until it's been merged). It includes some basic caching and our build times will be around 10-15 minutes when we are able to use the cache.

It does not remove any Travis configuration settings or alter anything with deployment yet, so it will just produce builds as we go along. I just figured this would be a good thing to merge for at least right now since it seems this latest HLint update to v3.3 seems to break down on Drasil -- I'm not quite sure why yet but I don't think it's a problem with Drasil (logs attached below).

If you'd like to preview what these end up looking like, please have a look at [these examples](https://github.com/balacij/Drasil/actions).

Related HLint issue:
```
curl --max-time 60 -sSL https://raw.github.com/ndmitchell/hlint/master/misc/run.sh | sh -s .
Downloading and running hlint...
######################################################################## 100.0%
drasil-example/Drasil/GamePhysics/DataDefs.hs:288:23: Error: Parse error: on input `-'
Found:
    coeffRestitutionEqn :: Expr
  > coeffRestitutionEqn = - sy finRelVel $.
      sy normalVect / sy initRelVel $.
      sy normalVect
  

drasil-example/Drasil/Projectile/IMods.hs:52:33: Error: Parse error: on input `-'
Found:
    timeDerivSent1 = foldlSentCol [S "We know that" +:+.
      foldlList Comma List [eqnWSource (sy iyPos $= 0) launchOrigin,
  >   eqnWSource (sy yConstAccel $= - sy gravitationalAccelConst) accelYGravity],
      S "Substituting these", plural value, S "into the y-direction" `sOf`
      makeRef2S posVecGD, S "gives us"]
  

drasil-example/Drasil/SSP/BasicExprs.hs:36:6-24: Suggestion: Redundant bracket
Found:
  (inxi intNormForce) + inxiM1 intNormForce
Perhaps:
  inxi intNormForce + inxiM1 intNormForce

drasil-example/Drasil/SSP/BasicExprs.hs:45:6-24: Suggestion: Redundant bracket
Found:
  (inxi intNormForce) + inxiM1 intNormForce
Perhaps:
  inxi intNormForce + inxiM1 intNormForce

drasil-example/Drasil/SSP/BasicExprs.hs:50:6-21: Suggestion: Redundant bracket
Found:
  (inxi watrForce) + inxiM1 watrForce
Perhaps:
  inxi watrForce + inxiM1 watrForce

drasil-example/Drasil/SSP/BasicExprs.hs:52:6-24: Suggestion: Redundant bracket
Found:
  (inxi intNormForce) + inxiM1 intNormForce
Perhaps:
  inxi intNormForce + inxiM1 intNormForce

drasil-example/Drasil/SSP/BasicExprs.hs:57:6-21: Suggestion: Redundant bracket
Found:
  (inxi watrForce) + inxiM1 watrForce
Perhaps:
  inxi watrForce + inxiM1 watrForce

drasil-example/Drasil/SSP/BasicExprs.hs:59:6-24: Suggestion: Redundant bracket
Found:
  (inxi intNormForce) + inxiM1 intNormForce
Perhaps:
  inxi intNormForce + inxiM1 intNormForce

drasil-example/Drasil/SSP/IMods.hs:302:21: Error: Parse error: on input `-'
Found:
    fctSftyDerivEqn12 :: Expr
  > fctSftyDerivEqn12 = - (sy fs * indxn shearFNoIntsl - indxn shearRNoIntsl) /
      idx (sy mobShrC) (sy numbSlices - int 1) $= 
      idx (sy intNormForce) (sy numbSlices - int 1) * 
  

9 hints
```

### CODE REVIEW

**Comment by JacquesCarette** [comment]
The last 4 you show in the examples all fail. Is it all because of hlint issues?  The redundant bracket thing should just be fixed.  The leading `-` problem seems to be a bug in hlint itself, no?  Has it been fixed?

**Review by JacquesCarette — APPROVED** [review]

**Comment by balacij** [comment]
The last 4 examples all fail because of HLint issues, yes.

The issue with `-` seems to be an issue related to [this proposal](https://github.com/ghc-proposals/ghc-proposals/blob/master/proposals/0229-whitespace-bang-patterns.rst) update in GHC 9. Since HLint strictly follows the latest version of GHC (as pointed out by the author [here](https://github.com/ndmitchell/hlint/issues/1212#issuecomment-798933988)), we might need to just rewrite them (wrapping them in parantheses) -- though I haven't yet tested against GHC 9 to see if the error should actually be popping up.

**Comment by balacij** [comment]
@JacquesCarette I keep forgetting that GitHub updates PRs as we commit. I just wanted to give this a quick go, seems to work with the latest commit and run but I'm not quite confident that the changes regarding the operator sections vs prefix negation don't impact our GHC version vs 9.0.

Should I create a new PR for strictly the HLint issues, for us to analyze them individually?

**Review by JacquesCarette — APPROVED** [review]

**Comment by JacquesCarette** [comment]
When we do PRs, we should go from clean build to clean build. So if things fail hlint, they need fixed in the same PR.

**Pull request merged**
