### PR TITLE
PR - fixHLint to master

### PR DESCRIPTION
**Pull request by danscime**
Fixed all currently known eta reductions.

### CODE REVIEW

**Comment by danscime** [comment]
So I have added back section'' and I will remove it via a different branch and PR.
Everything else in this PR is hlint related. Commits will be smaller in the future.

**Comment by JacquesCarette** [comment]
You'll need to merge master in first before I can merge - conflict in `Document.hs`.

**Comment by danscime** [comment]
It was used as if it the new change never happened. The changing from section'' to section would have happened afterwards. Regardless, it is resolved now.

**Comment by danscime** [comment]
So this PR can go through?

**Comment by JacquesCarette** [comment]
Travis now works, but master must be re-merged since there's now a conflict!

**Comment by danscime** [comment]
Conflict resolved.

**Pull request merged**
