### PR TITLE
Split Drasil into SubPackages

### PR DESCRIPTION
**Pull request by samm82**
The Drasil framework was split into `drasil-lang`, `drasil-code`, `drasil-data`, and `drasil-example` as per #558. I'm not really sure how this merge will affect branches of master though...

This branch can be deleted once merged - I'm going to make new branches for smaller changes in #558 (ie. making `drasil-printers`, etc.)

### CODE REVIEW

**Comment by JacquesCarette** [comment]
So this is, in theory, ready for merge?  We're going to want to coordinate quite heavily to do so.

**Comment by samm82** [comment]
I'm just merging master into it, and then yes, it is.

**Comment by JacquesCarette** [comment]
Note: I won't delete the branch quite yet, just in case things go horribly wrong.

**Comment by samm82** [comment]
I feel like I should make a wiki page to address common problems with this merge 😬 @JacquesCarette

**Comment by JacquesCarette** [comment]
Yes please!

**Comment by samm82** [comment]
The SubPackages branch now fails due to changes in master - how long should it be maintained for? Do you think its safe to delete it now? @JacquesCarette

**Pull request merged**
