### PR TITLE
Revert a reversion of #3553

### PR DESCRIPTION
**Pull request by balacij**
@samm82 in particular will need to audit these changes (to make sure I didn't revert any of his changes), but the reviewers list doesn't let me indicate this.

### CODE REVIEW

**Review by JacquesCarette — APPROVED** [review]

**Comment by JacquesCarette** [comment]
I'll merge once the build is clean.

**Review by samm82 — APPROVED** [review]
Sorry for reverting your changes 😔 it was an accident I swear 😭😭😭

**Comment by samm82** [comment]
@balacij In future if you want to specifically indicate someone's review, you could potentially assign them to the PR? That might be a good way to indicate that with the code owners

Speaking of which, I'm realizing that having Dong, Brooks, and myself (who are "owners" of certain examples) as code owners of their stable versions means we get assigned to many issues that don't directly impact us (e.g., rendering of code, etc.) - do people (I guess mainly @cd155 and @bmaclach) think I should modify the code owners file so that we only get added to PRs that modify files in `drasil-example` for our relevant examples or do you like the way it's set up now?

**Comment by balacij** [comment]
Yep, I normally add people directly to PRs. The code owners forcibly added everyone, so there was no special indication I could make other than descriptions.

**Pull request merged**
