### PR TITLE
Fixing .gitattributes file

### PR DESCRIPTION
**Pull request by balacij**
Closes #2184 

Example of what the code stats will end up looking like: https://github.com/balacij/Drasil/

Breakdown of what will be counted towards the code statistics with this configuration file: ~~SNIP: See below comments~~

### CODE REVIEW

**Comment by balacij** [comment]
Sorry for the huge initial post, I wish I could've made the code comment I posted in the OP collapsible, but I don't think we can on GitHub unfortunately without using pastebin or some similar service instead.

I think we should also remove the `Papers/*` from the `.gitattributes` file as well. Any thoughts on this @JacquesCarette @smiths ?

**Comment by smiths** [comment]
@balacij it is nice to see a summary like this.  It forces us to look at our repo from a different perspective.  

I like including the Papers, since they represent content that we wrote.  However, I don't feel that strongly about it.

I think the list of files you included is fine, since the number of "false positives" isn't that high.  However, if we are going to be picky, there are a few changes we could make:

1. Remove the tex related files that we didn't write.  As I said, I like including the papers, but the `cls` and `bst` files shouldn't be included, since we didn't write them.  We aren't likely to write files in these categories in the future either.
2. I think we should entirely remove `code/drasil-example/Drasil/Projectile/src`.  I don't mean  just from counting the files; I mean remove the src folder from the repo completely.  Projectile is the only example that has a src folder.  I believe we did this to provide a target to help us with experiments with the generator.  The generator now works for Projectile, so keeping this code doesn't really add anything of value.
3. We can delete `code/drasil-example/Drasil/PDController/report.html`.  Again, I mean we can entirely remove it from the repo.  This file is an hlint report and not really relevant in our repo.

**Comment by balacij** [comment]
Thank you @smiths for your great analysis. I understand what you mean about the Papers and I agree. I think it's best to keep them now as well (though I don't feel strongly either if anyone says otherwise).

I just removed `cls` and `bst` files from being added into the calculation.

Regarding 2 & 3, I will do these in separate PRs.

Here's an updated breakdown result:

```
89.92%  Haskell
8.19%   TeX
0.71%   Shell
0.47%   HTML
0.40%   Makefile
0.28%   Python
0.04%   CSS

TeX:
Papers/ContentsOfSS/ContentsOfSS.tex
Papers/GOOL/GOOL.tex
Papers/GOOL/GOOLarXiv.tex
Papers/GOOL/References.bib
Papers/GOOL/ResponseToReviewers.tex
Papers/GenerateEverything/GenerateEverything.tex
code/drasil-example/Drasil/Projectile/MG/MG.bib
code/drasil-example/Drasil/Projectile/MG/Projectile_MG.tex
code/drasil-example/Drasil/Projectile/MIS/MIS.bib
code/drasil-example/Drasil/Projectile/MIS/Projectile_MIS.tex

Makefile:
code/Makefile
code/drasil-example/Drasil/Projectile/src/Makefile
code/website/Makefile

Haskell:
code/drasil-build/Build/Drasil.hs
code/drasil-build/Build/Drasil/Make/AST.hs
code/drasil-build/Build/Drasil/Make/Helpers.hs
code/drasil-build/Build/Drasil/Make/Import.hs
code/drasil-build/Build/Drasil/Make/MakeString.hs
code/drasil-build/Build/Drasil/Make/Print.hs
code/drasil-code/Data/Drasil/ExternalLibraries/ODELibraries.hs
code/drasil-code/Language/Drasil/Choices.hs
code/drasil-code/Language/Drasil/Chunk/Code.hs
code/drasil-code/Language/Drasil/Chunk/CodeDefinition.hs
code/drasil-code/Language/Drasil/Chunk/Parameter.hs
code/drasil-code/Language/Drasil/Code.hs
code/drasil-code/Language/Drasil/Code/AST.hs
code/drasil-code/Language/Drasil/Code/Code.hs
code/drasil-code/Language/Drasil/Code/CodeGeneration.hs
code/drasil-code/Language/Drasil/Code/CodeQuantityDicts.hs
code/drasil-code/Language/Drasil/Code/DataDesc.hs
code/drasil-code/Language/Drasil/Code/ExtLibImport.hs
code/drasil-code/Language/Drasil/Code/ExternalLibrary.hs
code/drasil-code/Language/Drasil/Code/ExternalLibraryCall.hs
code/drasil-code/Language/Drasil/Code/Imperative/Build/AST.hs
code/drasil-code/Language/Drasil/Code/Imperative/Build/Import.hs
code/drasil-code/Language/Drasil/Code/Imperative/Comments.hs
code/drasil-code/Language/Drasil/Code/Imperative/ConceptMatch.hs
code/drasil-code/Language/Drasil/Code/Imperative/Descriptions.hs
code/drasil-code/Language/Drasil/Code/Imperative/Doxygen/Import.hs
code/drasil-code/Language/Drasil/Code/Imperative/DrasilState.hs
code/drasil-code/Language/Drasil/Code/Imperative/FunctionCalls.hs
code/drasil-code/Language/Drasil/Code/Imperative/GOOL/ClassInterface.hs
code/drasil-code/Language/Drasil/Code/Imperative/GOOL/Data.hs
code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer.hs
code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/CSharpRenderer.hs
code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/CppRenderer.hs
code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/JavaRenderer.hs
code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/LanguagePolymorphic.hs
code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/PythonRenderer.hs
code/drasil-code/Language/Drasil/Code/Imperative/GOOL/LanguageRenderer/SwiftRenderer.hs
code/drasil-code/Language/Drasil/Code/Imperative/GenODE.hs
code/drasil-code/Language/Drasil/Code/Imperative/GenerateGOOL.hs
code/drasil-code/Language/Drasil/Code/Imperative/Generator.hs
code/drasil-code/Language/Drasil/Code/Imperative/Helpers.hs
code/drasil-code/Language/Drasil/Code/Imperative/Import.hs
code/drasil-code/Language/Drasil/Code/Imperative/Logging.hs
code/drasil-code/Language/Drasil/Code/Imperative/Modules.hs
code/drasil-code/Language/Drasil/Code/Imperative/Parameters.hs
code/drasil-code/Language/Drasil/Code/Imperative/Parsers/ConfigParser.hs
code/drasil-code/Language/Drasil/Code/Imperative/ReadInput.hs
code/drasil-code/Language/Drasil/Code/Imperative/SpaceMatch.hs
code/drasil-code/Language/Drasil/Code/Imperative/WriteInput.hs
code/drasil-code/Language/Drasil/Code/Imperative/WriteReadMe.hs
code/drasil-code/Language/Drasil/Code/Lang.hs
code/drasil-code/Language/Drasil/CodeExpr.hs
code/drasil-code/Language/Drasil/CodeSpec.hs
code/drasil-code/Language/Drasil/Data/ODEInfo.hs
code/drasil-code/Language/Drasil/Data/ODELibPckg.hs
code/drasil-code/Language/Drasil/Mod.hs
code/drasil-code/Test/FileTests.hs
code/drasil-code/Test/HelloWorld.hs
code/drasil-code/Test/Helper.hs
code/drasil-code/Test/Main.hs
code/drasil-code/Test/Observer.hs
code/drasil-code/Test/PatternTest.hs
code/drasil-data/Data/Drasil/Citations.hs
code/drasil-data/Data/Drasil/Concepts/Computation.hs
code/drasil-data/Data/Drasil/Concepts/Documentation.hs
code/drasil-data/Data/Drasil/Concepts/Education.hs
code/drasil-data/Data/Drasil/Concepts/Math.hs
code/drasil-data/Data/Drasil/Concepts/PhysicalProperties.hs
code/drasil-data/Data/Drasil/Concepts/Physics.hs
code/drasil-data/Data/Drasil/Concepts/Software.hs
code/drasil-data/Data/Drasil/Concepts/SolidMechanics.hs
code/drasil-data/Data/Drasil/Concepts/Thermodynamics.hs
code/drasil-data/Data/Drasil/Constraints.hs
code/drasil-data/Data/Drasil/Equations/Defining/Physics.hs
code/drasil-data/Data/Drasil/People.hs
code/drasil-data/Data/Drasil/Quantities/Math.hs
code/drasil-data/Data/Drasil/Quantities/PhysicalProperties.hs
code/drasil-data/Data/Drasil/Quantities/Physics.hs
code/drasil-data/Data/Drasil/Quantities/SolidMechanics.hs
code/drasil-data/Data/Drasil/Quantities/Thermodynamics.hs
code/drasil-data/Data/Drasil/SI_Units.hs
code/drasil-data/Data/Drasil/Software/Products.hs
code/drasil-data/Data/Drasil/Theories/Physics.hs
code/drasil-data/Data/Drasil/Units/PhysicalProperties.hs
code/drasil-data/Data/Drasil/Units/Physics.hs
code/drasil-data/Data/Drasil/Units/SolidMechanics.hs
code/drasil-data/Data/Drasil/Units/Thermodynamics.hs
code/drasil-database/Database/Drasil.hs
code/drasil-database/Database/Drasil/ChunkDB.hs
code/drasil-database/Database/Drasil/ChunkDB/GetChunk.hs
code/drasil-database/Database/Drasil/SystemInformation.hs
code/drasil-docLang/Drasil/DocDecl.hs
code/drasil-docLang/Drasil/DocLang.hs
code/drasil-docLang/Drasil/DocLang/SRS.hs
code/drasil-docLang/Drasil/DocumentLanguage.hs
code/drasil-docLang/Drasil/DocumentLanguage/Core.hs
code/drasil-docLang/Drasil/DocumentLanguage/Definitions.hs
code/drasil-docLang/Drasil/DocumentLanguage/Labels.hs
code/drasil-docLang/Drasil/DocumentLanguage/RefHelpers.hs
code/drasil-docLang/Drasil/DocumentLanguage/TraceabilityMatrix.hs
code/drasil-docLang/Drasil/DocumentLanguage/Units.hs
code/drasil-docLang/Drasil/ExtractDocDesc.hs
code/drasil-docLang/Drasil/Sections/AuxiliaryConstants.hs
code/drasil-docLang/Drasil/Sections/GeneralSystDesc.hs
code/drasil-docLang/Drasil/Sections/Introduction.hs
code/drasil-docLang/Drasil/Sections/ReferenceMaterial.hs
code/drasil-docLang/Drasil/Sections/Requirements.hs
code/drasil-docLang/Drasil/Sections/SpecificSystemDescription.hs
code/drasil-docLang/Drasil/Sections/Stakeholders.hs
code/drasil-docLang/Drasil/Sections/TableOfAbbAndAcronyms.hs
code/drasil-docLang/Drasil/Sections/TableOfSymbols.hs
code/drasil-docLang/Drasil/Sections/TableOfUnits.hs
code/drasil-docLang/Drasil/Sections/TraceabilityMandGs.hs
code/drasil-docLang/Drasil/TraceTable.hs
code/drasil-example/Drasil/DblPendulum/Assumptions.hs
code/drasil-example/Drasil/DblPendulum/Body.hs
code/drasil-example/Drasil/DblPendulum/Concepts.hs
code/drasil-example/Drasil/DblPendulum/DataDefs.hs
code/drasil-example/Drasil/DblPendulum/Figures.hs
code/drasil-example/Drasil/DblPendulum/GenDefs.hs
code/drasil-example/Drasil/DblPendulum/Goals.hs
code/drasil-example/Drasil/DblPendulum/IMods.hs
code/drasil-example/Drasil/DblPendulum/Main.hs
code/drasil-example/Drasil/DblPendulum/Requirements.hs
code/drasil-example/Drasil/DblPendulum/Unitals.hs
code/drasil-example/Drasil/GamePhysics/Assumptions.hs
code/drasil-example/Drasil/GamePhysics/Body.hs
code/drasil-example/Drasil/GamePhysics/Changes.hs
code/drasil-example/Drasil/GamePhysics/Concepts.hs
code/drasil-example/Drasil/GamePhysics/DataDefs.hs
code/drasil-example/Drasil/GamePhysics/DesignDec/Arbiter.hs
code/drasil-example/Drasil/GamePhysics/DesignDec/Vector.hs
code/drasil-example/Drasil/GamePhysics/GDefs.hs
code/drasil-example/Drasil/GamePhysics/GenDefs.hs
code/drasil-example/Drasil/GamePhysics/Goals.hs
code/drasil-example/Drasil/GamePhysics/IMods.hs
code/drasil-example/Drasil/GamePhysics/Main.hs
code/drasil-example/Drasil/GamePhysics/References.hs
code/drasil-example/Drasil/GamePhysics/Requirements.hs
code/drasil-example/Drasil/GamePhysics/TMods.hs
code/drasil-example/Drasil/GamePhysics/Unitals.hs
code/drasil-example/Drasil/GlassBR/Assumptions.hs
code/drasil-example/Drasil/GlassBR/Body.hs
code/drasil-example/Drasil/GlassBR/Changes.hs
code/drasil-example/Drasil/GlassBR/Concepts.hs
code/drasil-example/Drasil/GlassBR/DataDefs.hs
code/drasil-example/Drasil/GlassBR/Figures.hs
code/drasil-example/Drasil/GlassBR/Goals.hs
code/drasil-example/Drasil/GlassBR/IMods.hs
code/drasil-example/Drasil/GlassBR/Main.hs
code/drasil-example/Drasil/GlassBR/ModuleDefs.hs
code/drasil-example/Drasil/GlassBR/References.hs
code/drasil-example/Drasil/GlassBR/Requirements.hs
code/drasil-example/Drasil/GlassBR/Symbols.hs
code/drasil-example/Drasil/GlassBR/TMods.hs
code/drasil-example/Drasil/GlassBR/Unitals.hs
code/drasil-example/Drasil/GlassBR/Units.hs
code/drasil-example/Drasil/HGHC/Body.hs
code/drasil-example/Drasil/HGHC/HeatTransfer.hs
code/drasil-example/Drasil/HGHC/Main.hs
code/drasil-example/Drasil/NoPCM/Assumptions.hs
code/drasil-example/Drasil/NoPCM/Body.hs
code/drasil-example/Drasil/NoPCM/Changes.hs
code/drasil-example/Drasil/NoPCM/DataDefs.hs
code/drasil-example/Drasil/NoPCM/Definitions.hs
code/drasil-example/Drasil/NoPCM/GenDefs.hs
code/drasil-example/Drasil/NoPCM/Goals.hs
code/drasil-example/Drasil/NoPCM/IMods.hs
code/drasil-example/Drasil/NoPCM/Main.hs
code/drasil-example/Drasil/NoPCM/References.hs
code/drasil-example/Drasil/NoPCM/Requirements.hs
code/drasil-example/Drasil/NoPCM/Unitals.hs
code/drasil-example/Drasil/PDController/Assumptions.hs
code/drasil-example/Drasil/PDController/Body.hs
code/drasil-example/Drasil/PDController/Changes.hs
code/drasil-example/Drasil/PDController/Concepts.hs
code/drasil-example/Drasil/PDController/DataDefs.hs
code/drasil-example/Drasil/PDController/GenDefs.hs
code/drasil-example/Drasil/PDController/GenSysDesc.hs
code/drasil-example/Drasil/PDController/IModel.hs
code/drasil-example/Drasil/PDController/IntroSection.hs
code/drasil-example/Drasil/PDController/Main.hs
code/drasil-example/Drasil/PDController/References.hs
code/drasil-example/Drasil/PDController/Requirements.hs
code/drasil-example/Drasil/PDController/SpSysDesc.hs
code/drasil-example/Drasil/PDController/TModel.hs
code/drasil-example/Drasil/Projectile/Assumptions.hs
code/drasil-example/Drasil/Projectile/Body.hs
code/drasil-example/Drasil/Projectile/Concepts.hs
code/drasil-example/Drasil/Projectile/DataDefs.hs
code/drasil-example/Drasil/Projectile/Expressions.hs
code/drasil-example/Drasil/Projectile/Figures.hs
code/drasil-example/Drasil/Projectile/GenDefs.hs
code/drasil-example/Drasil/Projectile/Goals.hs
code/drasil-example/Drasil/Projectile/IMods.hs
code/drasil-example/Drasil/Projectile/Main.hs
code/drasil-example/Drasil/Projectile/References.hs
code/drasil-example/Drasil/Projectile/Requirements.hs
code/drasil-example/Drasil/Projectile/Unitals.hs
code/drasil-example/Drasil/SSP/Assumptions.hs
code/drasil-example/Drasil/SSP/BasicExprs.hs
code/drasil-example/Drasil/SSP/Body.hs
code/drasil-example/Drasil/SSP/Changes.hs
code/drasil-example/Drasil/SSP/DataDefs.hs
code/drasil-example/Drasil/SSP/Defs.hs
code/drasil-example/Drasil/SSP/Figures.hs
code/drasil-example/Drasil/SSP/GenDefs.hs
code/drasil-example/Drasil/SSP/Goals.hs
code/drasil-example/Drasil/SSP/IMods.hs
code/drasil-example/Drasil/SSP/Main.hs
code/drasil-example/Drasil/SSP/References.hs
code/drasil-example/Drasil/SSP/Requirements.hs
code/drasil-example/Drasil/SSP/TMods.hs
code/drasil-example/Drasil/SSP/Unitals.hs
code/drasil-example/Drasil/SWHS/Assumptions.hs
code/drasil-example/Drasil/SWHS/Body.hs
code/drasil-example/Drasil/SWHS/Changes.hs
code/drasil-example/Drasil/SWHS/Concepts.hs
code/drasil-example/Drasil/SWHS/DataDefs.hs
code/drasil-example/Drasil/SWHS/GenDefs.hs
code/drasil-example/Drasil/SWHS/Generate.hs
code/drasil-example/Drasil/SWHS/Goals.hs
code/drasil-example/Drasil/SWHS/IMods.hs
code/drasil-example/Drasil/SWHS/Main.hs
code/drasil-example/Drasil/SWHS/References.hs
code/drasil-example/Drasil/SWHS/Requirements.hs
code/drasil-example/Drasil/SWHS/TMods.hs
code/drasil-example/Drasil/SWHS/Unitals.hs
code/drasil-example/Drasil/Template/Body.hs
code/drasil-example/Drasil/Template/Main.hs
code/drasil-gen/Language/Drasil/Generate.hs
code/drasil-gen/Language/Drasil/Output/Formats.hs
code/drasil-gool/GOOL/Drasil.hs
code/drasil-gool/GOOL/Drasil/AST.hs
code/drasil-gool/GOOL/Drasil/ClassInterface.hs
code/drasil-gool/GOOL/Drasil/Classes.hs
code/drasil-gool/GOOL/Drasil/CodeAnalysis.hs
code/drasil-gool/GOOL/Drasil/CodeInfo.hs
code/drasil-gool/GOOL/Drasil/CodeType.hs
code/drasil-gool/GOOL/Drasil/Helpers.hs
code/drasil-gool/GOOL/Drasil/LanguageRenderer.hs
code/drasil-gool/GOOL/Drasil/LanguageRenderer/CLike.hs
code/drasil-gool/GOOL/Drasil/LanguageRenderer/CSharpRenderer.hs
code/drasil-gool/GOOL/Drasil/LanguageRenderer/CommonPseudoOO.hs
code/drasil-gool/GOOL/Drasil/LanguageRenderer/Constructors.hs
code/drasil-gool/GOOL/Drasil/LanguageRenderer/CppRenderer.hs
code/drasil-gool/GOOL/Drasil/LanguageRenderer/JavaRenderer.hs
code/drasil-gool/GOOL/Drasil/LanguageRenderer/LanguagePolymorphic.hs
code/drasil-gool/GOOL/Drasil/LanguageRenderer/Macros.hs
code/drasil-gool/GOOL/Drasil/LanguageRenderer/PythonRenderer.hs
code/drasil-gool/GOOL/Drasil/LanguageRenderer/SwiftRenderer.hs
code/drasil-gool/GOOL/Drasil/RendererClasses.hs
code/drasil-gool/GOOL/Drasil/State.hs
code/drasil-lang/Language/Drasil.hs
code/drasil-lang/Language/Drasil/Chunk/Citation.hs
code/drasil-lang/Language/Drasil/Chunk/CommonIdea.hs
code/drasil-lang/Language/Drasil/Chunk/Concept.hs
code/drasil-lang/Language/Drasil/Chunk/Concept/Core.hs
code/drasil-lang/Language/Drasil/Chunk/Constrained.hs
code/drasil-lang/Language/Drasil/Chunk/DefinedQuantity.hs
code/drasil-lang/Language/Drasil/Chunk/Eq.hs
code/drasil-lang/Language/Drasil/Chunk/NamedArgument.hs
code/drasil-lang/Language/Drasil/Chunk/NamedIdea.hs
code/drasil-lang/Language/Drasil/Chunk/Quantity.hs
code/drasil-lang/Language/Drasil/Chunk/Relation.hs
code/drasil-lang/Language/Drasil/Chunk/UncertainQuantity.hs
code/drasil-lang/Language/Drasil/Chunk/UnitDefn.hs
code/drasil-lang/Language/Drasil/Chunk/Unital.hs
code/drasil-lang/Language/Drasil/Chunk/Unitary.hs
code/drasil-lang/Language/Drasil/Chunk/UnitaryConcept.hs
code/drasil-lang/Language/Drasil/Classes.hs
code/drasil-lang/Language/Drasil/Classes/Citations.hs
code/drasil-lang/Language/Drasil/Classes/Core.hs
code/drasil-lang/Language/Drasil/Classes/Document.hs
code/drasil-lang/Language/Drasil/Constraint.hs
code/drasil-lang/Language/Drasil/Data/Citation.hs
code/drasil-lang/Language/Drasil/Data/Date.hs
code/drasil-lang/Language/Drasil/Derivation.hs
code/drasil-lang/Language/Drasil/Development.hs
code/drasil-lang/Language/Drasil/Development/Sentence.hs
code/drasil-lang/Language/Drasil/Document.hs
code/drasil-lang/Language/Drasil/Document/Core.hs
code/drasil-lang/Language/Drasil/Expr.hs
code/drasil-lang/Language/Drasil/Expr/Extract.hs
code/drasil-lang/Language/Drasil/Expr/Math.hs
code/drasil-lang/Language/Drasil/Expr/Precedence.hs
code/drasil-lang/Language/Drasil/Label/Type.hs
code/drasil-lang/Language/Drasil/Misc.hs
code/drasil-lang/Language/Drasil/NounPhrase.hs
code/drasil-lang/Language/Drasil/NounPhrase/Core.hs
code/drasil-lang/Language/Drasil/People.hs
code/drasil-lang/Language/Drasil/RefProg.hs
code/drasil-lang/Language/Drasil/Reference.hs
code/drasil-lang/Language/Drasil/Sentence.hs
code/drasil-lang/Language/Drasil/Sentence/Extract.hs
code/drasil-lang/Language/Drasil/ShortHands.hs
code/drasil-lang/Language/Drasil/ShortName.hs
code/drasil-lang/Language/Drasil/Space.hs
code/drasil-lang/Language/Drasil/Stages.hs
code/drasil-lang/Language/Drasil/Symbol.hs
code/drasil-lang/Language/Drasil/Symbol/Helpers.hs
code/drasil-lang/Language/Drasil/UID.hs
code/drasil-lang/Language/Drasil/URI/AST.hs
code/drasil-lang/Language/Drasil/Uncertainty.hs
code/drasil-lang/Language/Drasil/Uncertainty/Core.hs
code/drasil-lang/Language/Drasil/Unicode.hs
code/drasil-lang/Language/Drasil/UnitLang.hs
code/drasil-metadata/Data/Drasil/Domains.hs
code/drasil-printers/Language/Drasil/Config.hs
code/drasil-printers/Language/Drasil/Format.hs
code/drasil-printers/Language/Drasil/HTML/CSS.hs
code/drasil-printers/Language/Drasil/HTML/Helpers.hs
code/drasil-printers/Language/Drasil/HTML/Monad.hs
code/drasil-printers/Language/Drasil/HTML/Print.hs
code/drasil-printers/Language/Drasil/Markdown/CreateMd.hs
code/drasil-printers/Language/Drasil/Plain/Helpers.hs
code/drasil-printers/Language/Drasil/Plain/Print.hs
code/drasil-printers/Language/Drasil/Printers.hs
code/drasil-printers/Language/Drasil/Printing/AST.hs
code/drasil-printers/Language/Drasil/Printing/Citation.hs
code/drasil-printers/Language/Drasil/Printing/Helpers.hs
code/drasil-printers/Language/Drasil/Printing/Import.hs
code/drasil-printers/Language/Drasil/Printing/LayoutObj.hs
code/drasil-printers/Language/Drasil/Printing/PrintingInformation.hs
code/drasil-printers/Language/Drasil/TeX/Helpers.hs
code/drasil-printers/Language/Drasil/TeX/Monad.hs
code/drasil-printers/Language/Drasil/TeX/Preamble.hs
code/drasil-printers/Language/Drasil/TeX/Print.hs
code/drasil-theory/Data/Drasil/TheoryConcepts.hs
code/drasil-theory/Theory/Drasil.hs
code/drasil-theory/Theory/Drasil/Classes.hs
code/drasil-theory/Theory/Drasil/DataDefinition.hs
code/drasil-theory/Theory/Drasil/GenDefn.hs
code/drasil-theory/Theory/Drasil/InstanceModel.hs
code/drasil-theory/Theory/Drasil/ModelKinds.hs
code/drasil-theory/Theory/Drasil/Theory.hs
code/drasil-utils/Utils/Drasil.hs
code/drasil-utils/Utils/Drasil/Contents.hs
code/drasil-utils/Utils/Drasil/Document.hs
code/drasil-utils/Utils/Drasil/English.hs
code/drasil-utils/Utils/Drasil/Fold.hs
code/drasil-utils/Utils/Drasil/Misc.hs
code/drasil-utils/Utils/Drasil/Phrase.hs
code/drasil-utils/Utils/Drasil/Sentence.hs
code/scripts/DataTableGen.hs
code/scripts/DirectoryController.hs
code/scripts/SourceCodeReader.hs
code/website/Main.hs
code/website/StringUtils.hs

Shell:
code/drasil-example/Drasil/PDController/FormatAll.sh
code/scripts/check_binary.sh
code/scripts/check_stack.sh
code/scripts/ci_functions.bash
code/scripts/code_build.sh
code/scripts/code_path.sh
code/scripts/deploy.bash
code/scripts/deploy_stage.sh
code/scripts/deploy_wrapper.bash
code/scripts/gooltest_build.sh
code/scripts/log_check.sh
code/scripts/maybe_test_deploy.sh
code/scripts/tex_build.sh

HTML:
code/drasil-example/Drasil/PDController/report.html
code/website/index.html
code/website/templates/base.html

Python:
code/drasil-example/Drasil/Projectile/src/Calculations.py
code/drasil-example/Drasil/Projectile/src/Control.py
code/drasil-example/Drasil/Projectile/src/InputConstraints.py
code/drasil-example/Drasil/Projectile/src/InputFormat.py
code/drasil-example/Drasil/Projectile/src/InputParameters.py
code/drasil-example/Drasil/Projectile/src/OutputFormat.py
code/scripts/pr_label_update.py

CSS:
code/website/css/styles.css

```

**Comment by JacquesCarette** [comment]
Agree with everything @smiths mentions. Including removing Projectile/src.  [What about Projectile/MIS and /MIG ?]

**Pull request merged**
