### PR TITLE
SSP Functional Requirements

### PR DESCRIPTION
**Pull request by bmaclach**
This PR updates the Functional Requirements section of SSP to match manual.

### CODE REVIEW

**Comment by bmaclach** [comment]
@smiths Good point, I added the requested requirement.

**Comment by smiths** [comment]
Thanks @bmaclach.  The new file output requirement looks good to me.

**Comment by JacquesCarette** [comment]
And this one needs a `master` merge.

**Comment by bmaclach** [comment]
Merged master.

**Pull request merged**
