### PR TITLE
Add 5 Projectiles to stable

### PR DESCRIPTION
**Pull request by bmaclach**
This PR updates our Travis builds to build 5 different versions of Projectile covering a range of `Choice` combinations, and adds all 5 versions to stable. This is as discussed in #2010.

### CODE REVIEW

**Comment by bmaclach** [comment]
The Choices that change between these examples are below. Beside each option, in brackets I've put a possible short form for that option.

Modularity - `Unmodular` [U], `Modular Combined` (one input module) [C], `Modular Separated` (multiple modules related to input) [S]

Logging - None [NoL] or All [L]

Comments - None [NoC] or All [C]

Input Structure - `Bundled` [B] or `Unbundled` [U]

Constant structure - `Bundled` [B] or `Unbundled` [U] or `WithInputs` [WI]

Constant representation - `Var` [V] or `Const` [C]

We can use underscores to separate the different choices, ending up with file names like: Projectile_U_NoL_NoC_U_WI_V. Would that be okay?

We have also talked in the past about documenting the chosen options for the examples in stable in some sort of table on the webpage. I can't find an open issue for it, but I remember it not being straightforward which is why it wasn't done (I think the idea we were thinking of was `grep`-ing the code to find the `Choices` structure for each example, then extracting the `Choices` from there, but that's a really fragile solution).

**Comment by smiths** [comment]
@bmaclach, I like your proposal for naming the folders.  We should record the codes somewhere, so that someone can interpret the folder names.  Maybe this would make sense in the introduction blurb for the generated artifacts web-page (https://jacquescarette.github.io/Drasil/)?

Yes, we have discussed documenting the variability choices for the case studies.  I like the idea of automating this, so that if the choices change, so does the documentation.  However, we have intentionally selected these examples, as you did for Projectile, maybe for now we can just "hard code" the choices.  The choices could go in the introductory blurb for the web-page I mentioned above.  There is a maintainability concern, but until we have a more elegant solution, just recording the information somewhere makes sense to me.

**Comment by bmaclach** [comment]
Okay @smiths, I'll add the table and short-form guide to the website intro blurb. I agree that it would be good to record it, even if that means hard-coding it for now.

**Comment by smiths** [comment]
Sounds good @bmaclach.  Maybe you should also create an issue to remind us to circle back to this to find a more maintainable generative approach in the future?

**Comment by bmaclach** [comment]
I just pushed a bunch of changes. First, I made the requested changes:
1. Changed folder names to encode design decisions
2. Added to website table showing design decisions for each example
3. Added to website guide for decoding the short forms for the design decisions

I then realized that because updating projectile to have multiple versions changed the directory structure for projectile in stable, the links to Projectile src code/doxygen pages were broken on the website. I updated our Makefiles/scripts/website code to handle the scenario where an example has multiple versions, and added some formatting to the website to display links for each version in a nice list:
image

This had the side effect of making a list even for examples with only one version, but I think this still looks nice:
image

I think I've made these changes in a generic enough way that, should we ever decide to host multiple versions of another case study, we need only add the corresponding directory to the `MULTI_SRC_DIRS` Makefile variable, and the build process and website should be automatically updated to build/show all versions of the example.

**Comment by bmaclach** [comment]
Also created issue #2017 for automating the table of design decisions in the future.

**Pull request merged**
