### PR TITLE
PR - More hlint camel case

### PR DESCRIPTION
**Pull request by danscime**
A lot of camel case linting fixes throughout project.

### CODE REVIEW

**Comment by danscime** [comment]
Resolved.

**Comment by samm82** [comment]
@danscime The GlassBR log isn't empty in this branch - just a heads up

**Comment by danscime** [comment]
Fixed.

**Comment by JacquesCarette** [comment]
Sorry, I did some more merges, and now there are more conflicts. This is the danger of huge PRs.

**Comment by danscime** [comment]
No problem. Merged.

**Comment by JacquesCarette** [comment]
Sorry, in the meantime I merged something else in! I'll wait so that this doesn't happen yet another time!

**Comment by danscime** [comment]
All good, merged.

**Pull request merged**
