### PR TITLE
Update SSP Stable for updates in manual version

### PR DESCRIPTION
**Pull request by niazim3**
Originates from work in smiths/caseStudies#35.

### CODE REVIEW

**Comment by smiths** [comment]
@niazim3, the changes look good to me, but, to keep our division of responsibilities consistent, I will leave it to @szymczdm or @JacquesCarette to approve the pull request.

**Comment by niazim3** [comment]
Since this branch has not been merged yet, the previous and next few commits are in relation to smiths/caseStudies#39.

**Comment by JacquesCarette** [comment]
So we should wait a little before merging?

**Comment by niazim3** [comment]
Yes, I suppose. I'll close this PR and reopen it when I'm done with the stable updates.

**Comment by niazim3** [comment]
This PR is starting to get large, so I think it would be beneficial to have it reviewed and merged into master sooner than later. The changes to the `parnas1986` implementation instances are discussed in further detail in issue #680.

**Pull request merged**
