### PR TITLE
Small change to ChunkDB

### LINKED ISSUE #2411: Error from using xPos and yPos in DblPendulum
```cd "build/DblPendulum" && stack exec -- "dblpendulum" 
dblpendulum.EXE: Symbol: yPos not found in SymbolMap
CallStack (from HasCallStack):
  error, called at ./Database\Drasil\ChunkDB.hs:81:24 in drasil-database-0.1.1.0-1H2SDTZem9VDdavf3C6Z5k:Database.Drasil.ChunkDB
make: *** [Makefile:142: dblpendulum_gen] Error 1
```
When trying to use the `xPos` or `yPos` symbols in `dblpendulum`, I received the above error. However, switching those out with `ixPos` and `iyPos` seems to make the error go away.

### PR DESCRIPTION
**Pull request by Ant13731**
Small PR, documented the `ChunkDB` type with a little bit more detail. Closes #2411 for now. I will probably take a look at the entire folder once I am more familiar with the functions/chunk system.

### CODE REVIEW

**Comment by Ant13731** [comment]
Some of the Mapping data types are not included in the haddock documentation (even though they have the proper comment syntax) as they do not import to `Database.Drasil`. Should they be imported or is there a way to get the documentation out of the nested files?

**Review by JacquesCarette — APPROVED** [review]

**Comment by JacquesCarette** [comment]
I think you mean that some don't show up in the Haddock because they are not exported from this current file?  Imports don't change anything wrt visibility, but export does. And what do you mean here by 'nested file'?

**Comment by Ant13731** [comment]
Yes, that's what I meant. By nested files I mean that the haddock documentation really only documents the main file (in this case, `Database.Drasil`) instead of all the smaller files that will eventually be imported (and exported) by `Database.Drasil`. In better wording, is there a way for the haddock documentation to "see" some of the types that are not exported?

**Comment by balacij** [comment]
@Ant13731 Yep, we're going to work on the Haddock docs in #2294 once the gh-pages automation is done (soon!). We previously discussed having external vs internal Haddock docs where the external one is fairly minimal in comparison to the internal one (which would show everything [excluding external dependencies]).

Right now the docs are deployed using https://github.com/JacquesCarette/Drasil/blob/5fbcb79c17aa8c7820abac644ddb23a38ea1ee64/.github/workflows/Drasil.yaml#L69 which causes a bit of problems as you already noticed.

The main issue lies in which modules are exposed in our package.yaml files, we just need to override them with the haddock args.

**Comment by Ant13731** [comment]
Okay I see. Sounds good!

**Pull request merged**
