### PR TITLE
Gamephy - Added Impulse to Datadefs.hs

### PR DESCRIPTION
**Pull request by oluowoj**
@Carette, looks like the equation I wrote works well afterall. 
I added new parameters into Concept, Quantities and Unitals.hs for chgMomentum(change in momentum), and chgInVelocity (change in velocity) and I was able to arrive at this formula.

Manual version equation: 
image

Drasil version equation:
image

### CODE REVIEW

**Comment by JacquesCarette** [comment]
Things to do:
1. merge master in here (to resolve the conflicts)
2. make CI pass
3. file that issue
and then I will merge this in.  With the multi-equation as is.

**Comment by oluowoj** [comment]
I had to fix the issues we discussed in the hand-on meeting last Friday for Impulse(vector). So I did not merge the initial commit I had before the meeting. I am creating a new pull request for my most recent change

**Comment by oluowoj** [comment]
@JacquesCarette, you can remove this branch, I'm seeing too many issues and when I resolve them, some new ones come up, so I will work on a new branch and make all the changes on that branch.

**Comment by JacquesCarette** [comment]
You know that you pushed 5 more changes to this branch after you said you'd stop working on this one and start fresh, right?

**Comment by oluowoj** [comment]
> You know that you pushed 5 more changes to this branch after you said you'd stop working on this one and start fresh, right?

yes, I thought i'd  try a few more things if it would resolve the issues. I still have the branch in my locals

**Comment by JacquesCarette** [comment]
Should this PR be closed, or are you still trying to 'rescue' it?

**Comment by oluowoj** [comment]
This can be closed, I made this changes on a new branch

**Comment by JacquesCarette** [comment]
And deleted the branch too, to clean up.

**Pull request closed without merging**
