### PR TITLE
Additional paragraphs in IM section

### PR DESCRIPTION
**Pull request by bmaclach**
This PR updates the `DocLang` to allow for additional paragraphs to be added to the beginning of the instance model section, as discussed in #1205. For now, none of the case studies use this. I will update SWHS and SSP in future PRs.

### CODE REVIEW

**Comment by bmaclach** [comment]
Looking at all of the manual versions of the case studies, none of them have any additional paragraphs in the Theoretical Models, General Definitions, or Data Definitions sections. @smiths Can you foresee a scenario where we would want additional paragraphs for those sections?

**Comment by smiths** [comment]
Yes, I can see scenarios where we need custom text to introduce the theoretical models, general definitions etc.  We might want to orient the reader to the reasoning for classifying some particular thing as a theoretical model, for instance, or maybe we might want to explain a relationship that exists between the general definitions.  However, the fact that this hasn't previously comes up suggests that it isn't a high priority.

In my opinion, if making DocLang more general to consider problem specific text for the different sections makes the design more uniform, we should do it.  If the change is tacked on and unnatural, we shouldn't do it.  I certainly wouldn't suggest that we spend a great deal of time on implementing DocLang support for problem specific text in theoretical models, etc.  We should only do it at this time if it is a relatively easy task.  If it is time consuming, we can put it off until the date in the future when the need for this kind of problem specific customization arises.

**Comment by bmaclach** [comment]
Since I've already implemented it for the Instance Models section, doing the same for the other sections should be very easy. I expect the changes I will have to make for them will be directly analogous to the ones I've already made for Instance Models, so my vote would be to add the functionality for the rest of them now, to keep things consistent.

Then the only question is the one regarding the order of parameters. I think it makes sense to have the `[Sentence]` first since that introduction text will be rendered at the beginning of the section in question. @JacquesCarette if you agree, I'll go ahead and make the updates (adding the `[Sentence]` parameter to TMs, GDs, and DDs). Also, is it okay to do them all in this PR? Or a separate PR for each section?

**Comment by JacquesCarette** [comment]
I agree that, in this case, it makes sense to have the new argument be first. Since they are all related, it makes sense to do them in this PR (but if you've already done this in separate PRs, that's fine too).

**Comment by bmaclach** [comment]
Added the same functionality for TMs, GDs, and DDs.

**Pull request merged**
