### PR TITLE
Remove space before colon in Python files

### PR DESCRIPTION
**Pull request by harmanpreet-sagar**
Contributes to #3221. Removes spaces before the colon in Python files, making it more PEP8 compliant. Changes have been made to `drasil-gool` and stable.

### CODE REVIEW

**Review by smiths — APPROVED** [review]
The changes to stable look good to me.  I seem to remember a previous attempt to fix this that had an unwanted consequence on the generation of the other programming languages, but there are no changes in stable to any of the other languages, so there are no problems on that front.

**Comment by JacquesCarette** [comment]
Strictly speaking, I'm not super keen on this method of fixing the problem. It's a hack. I think that Python should choose to have its own renderer for `if` statements rather than over-engineering the language-polymorphic version with things that only Python cares about.

**Comment by smiths** [comment]
Makes sense @JacquesCarette.   Should we create an issue to add the Python rendered for `if` statements?

**Comment by JacquesCarette** [comment]
I'm thinking it's not worth bothering - we may as well wait until we have someone that needs to do a substantial refactor.

**Pull request merged**
