### PR TITLE
Update Stack minor version

### PR DESCRIPTION
**Pull request by balacij**
Bumping from GHC 9.2.5 to 9.2.7 with the updated Stackage lists.

### CODE REVIEW

**Comment by balacij** [comment]
@samm82 is it possible to remove people from the Stack YAML code ownership file?

**Comment by samm82** [comment]
@balacij Yeah, it should be - who should be auto-assigned for review? Just @JacquesCarette?

**Comment by balacij** [comment]
If it's possible, for the `stack.yaml` and `package.yaml` files, me too, but yes, @JacquesCarette for just about everything.

**Comment by samm82** [comment]
@balacij This PR or a new one?

**Comment by balacij** [comment]
Let's go with a new PR just to keep our pickiness normalized. Thank you very much @samm82 :smile:

**Comment by JacquesCarette** [comment]
I think I'm assigned for 'everything' right now, yes?

**Review by JacquesCarette — APPROVED** [review]

**Pull request merged**
