### PR TITLE
Functional Requirements Overhaul

### LINKED ISSUE #1403: FReqsSub Should take [ConceptInstance]?
_Related to #1023, as well as #1229 and its bunny trail of related issues._ (Not sure if there is already an issue specifically for this, but I couldn't find one.)

I was about to implement the Requirements for Projectile, but realized that it would probably make more sense to revise this code before adding another example that will break it.

https://github.com/JacquesCarette/Drasil/blob/8d0bbbea5633ce5c7a43f487757562ddca5d21b9/code/drasil-docLang/Drasil/DocumentLanguage.hs#L197-L199

Since `NonFReqsSub` was refactored to take a `[ConceptInstance]`, it makes sense that `FReqsSub` should be as well.

I don't want to step on anyone's toes, so @bmaclach, @Mornix, @JacquesCarette, @smiths, and/or anyone else feel free to let me know if this issue should be reassigned, pushed to later, or tackled now.

# TODO
- [x] GamePhysics
- [x] GlassBR
- [x] NoPCM
- [x] SSP
- [x] SWHS
- [x] Replace `FReqsSub` with `FReqsSub'`

_Closed with merge of #1461_

### LINKED ISSUE #1440: Consistency in Input Requirements Tables
This came up in a roundabout way from #1390, but the input requirements table (if present in an example) should be made consistent and moved (to `docLang` - `Requirements.hs`)? I'm personally fond of GlassBR's representation. The differences are the headers and the order of the columns. Thoughts? @smiths @JacquesCarette 

glassBR
ssp
swhs

### LINKED ISSUE #1460: Switch to Tables Instead of Lists in GlassBR Func Reqs
The fact that these FRs are represented as lists presents issues for #1403. Would it be acceptable to represent them as labelled ~lists~ tables instead, with columns Symbol, Description, Source, and Units?

image

### PR DESCRIPTION
**Pull request by samm82**
- Changed `FReqsSub` to take `[ConceptInstance]` (FRs) and `[LabelledContent]` (tables) (Closes #1403)
- Switched from lists to tables in GlassBR FRs by creating a `mkValsSourceTable` in `docLang` to build a table from list of tuples of (Quantity, Referable) (Closes #1460)
- Created a `mkInputPropsTable` in `docLang` to generate consistent input properties tables for the functional requirements section (Closes #1440)
- Removed SSP.Labels, SWHS.Tables, and SWHS.Labels, as they are no longer used

### CODE REVIEW

**Comment by samm82** [comment]
Closed until #1444 is merged into this

**Comment by JacquesCarette** [comment]
And the build failed (because of warnings).

**Comment by samm82** [comment]
Just fixed

**Comment by samm82** [comment]
The only reason this PR was so big was because I merged two branches together. There were too many changes that depended on each other in the separate branches.

**Comment by JacquesCarette** [comment]
Fair enough.

**Pull request merged**
