### PR TITLE
SSP SpencerFixme Fixes

### PR DESCRIPTION
**Pull request by bmaclach**
This PR gives meaningful names/symbols/descriptions to the SpencerFixme's, as requested in #1150.

### CODE REVIEW

**Comment by bmaclach** [comment]
Forgot to make the required references to populate the RefBy fields. Closing this PR until I get those changes in.

**Comment by bmaclach** [comment]
The missing references have been added.

**Comment by JacquesCarette** [comment]
Please merge master in here as well.

**Comment by bmaclach** [comment]
Master merged, should be good to go.

**Comment by JacquesCarette** [comment]
This one was good.  In it goes.

**Pull request merged**
