### PR TITLE
Added new definition into DataDefs.hs(Relative Velocity in Collision)

### PR DESCRIPTION
**Pull request by oluowoj**
Files updated are:
example/Drasil/GamePhysics/DataDefs.hs
example/Drasil/GamePhysics/Unitals.hs

The description for Relative Velocity in Collision will be updated in the next pull request. 
I am thinking I could improve how I derived the equation, still working on it and will create another pull request if I am able to get the code to run. For now, this derivation should suffice.

### CODE REVIEW

**Comment by oluowoj** [comment]
Merge master as requested

**Comment by JacquesCarette** [comment]
Unfortunately the builds now fail, as new warnings are now hard errors. So you'll need to fix that before I can merge!

**Comment by oluowoj** [comment]
@JacquesCarette @Mornix, @bmaclach 
would you know why this is happening:
@JacquesCarette  comment above, that "IM3 now links to a DD, and LC1, LC2 and LC3 link to IMs"
I am still trying to figure out what's causing this. I have added a couple of new modules in dataDefs.hs but in traceability matrix, I don't see new DD ids for these, rather these new DD's are linked to IMs as you mentioned. Its so weird. Any clues?

**Comment by bmaclach** [comment]
@oluowoj I'm not sure what's happening but it doesn't seem to be related to your changes. Even in the "before" part of the diff, the IM's are linking to DD's and LC's to IM's, etc. So this seems to be a longstanding issue where the labels in these traceability matrices don't match the section to which they link.

**Comment by JacquesCarette** [comment]
Well spotted @bmaclach ! Hmm, we need to look more deeply at all our examples then. If they are all weird like this (on master), then we have a big bug that needs fixed. [And it has nothing to do with this change]. Or is it just this example?  

Also, the builds are failing - @Mornix is this expected?

**Comment by Mornix** [comment]
Yup. This failure is expected. Compiling shows there are unused import warnings.

**Comment by oluowoj** [comment]
I will create an issue log for this one and take a look at other examples. Thanks all for the feedback

**Comment by JacquesCarette** [comment]
Travis now passes, but now there are new conflicts...

**Comment by oluowoj** [comment]
Looking into this, I see #1161 has been merged, this will help me to resolve the conflicts I hope

**Comment by JacquesCarette** [comment]
I think you'll need to merge master in here yet one more time.  And the build failed...

**Comment by oluowoj** [comment]
finally, conflicts resolved

**Pull request merged**
