### PR TITLE
Lowercase Example Folder Names

### LINKED ISSUE #1686: Capitalization Consitency In Folders Containing Examples
In build, stable, and drasil-example, we have different capitalization styles for the folders.
Very minor but I feel like they should be consistent.

build
stable
example

I believe @Mornix prefers folder names to be lowercase.
@smiths @JacquesCarette

### PR DESCRIPTION
**Pull request by Ant13731**
Closes #1686 
Contributes #2723 

- Renamed `analysis/DataTable` to `analysis/ClassInstDep` for better clarity
- example folders are all lowercase in `datafiles`, `build`, `traceygraphs` (and changed example files to match the new names)

There will probably be a merge conflict with #2744 so that should be merged first (it will be easier to fix that way)

### CODE REVIEW

**Comment by JacquesCarette** [comment]
As you guessed, there are now merge conflicts to resolve.

**Comment by JacquesCarette** [comment]
3495 files changed!?! I didn't know there were even that many files in this repo!

**Comment by Ant13731** [comment]
Yea, all the files in `datafiles` had to be moved (there is a surprising amount for the code dependencies).

**Comment by JacquesCarette** [comment]
I can't review the files that come after `datafiles` (it only allows me to see 3000 changes).  But the build works, so I'll believe that it's ok.

**Review by JacquesCarette — APPROVED** [review]

**Comment by Ant13731** [comment]
I'm going to test to make sure it works as expected on my Linux subsystem (and also test the deploy), so I'll mark it as a draft for now.

**Comment by Ant13731** [comment]
For the different Projectile versions, do we want the options to be lowercase as well? For example, the old version is `Projectile_C_P_NoL_B_U_V_D`. Since the examples are all lowercase now, it looks a little out of place. Should it become `projectile_C_P_NoL_B_U_V_D`, `projectile_c_p_nol_b_u_v_d` or should I find a way to keep it as it used to be (as `Projectile_C_P_NoL_B_U_V_D`)?

**Comment by JacquesCarette** [comment]
We should keep the names consistently lower-case (so `projectile`). Whether to lower-case everything or not, I'd kind of want to say "I don't care". But practically, because of trying to work on different OS with different notions of capitalization, we should probably lower-case everything, i.e. go with `projectile_c_p_nol_b_u_v_d`.

**Comment by Ant13731** [comment]
I'm going to test the deploy and make sure everything works on my forked repo. The new website with all the right (lowercase) folder paths will be [here](https://ant13731.github.io/Drasil/) when it is done deploying.

**Comment by Ant13731** [comment]
Okay, I think everything works with the new capitalization now!

**Comment by balacij** [comment]
I had no issues with this, but Awurama just right now had an issue with it. When running `git pull` whilst on the master branch did not update the stable folder properly. Specifically, those Project_X_Y_Z folders were not made lowercase. I guess this was a problem with MacOS. It resulted in her `master` branch always giving errors.

If anyone's on Mac, you might need to check out master, run `git pull`, delete the stable folder (this is just to force it to remake it), and then run `git reset --hard` to forcibly undo that deletion, but this time it will create the proper capitalization.

**Pull request merged**
