### PR TITLE
Remove greek

### PR DESCRIPTION
**Pull request by deviprasad135**
#481

### CODE REVIEW

**Comment by JacquesCarette** [comment]
@deviprasad135 This still breaks the build -- why haven't you fixed this yet?

**Comment by deviprasad135** [comment]
@JacquesCarette The stable version is using greek names. These are the differences showing in log files. Should I update the stable version?

**Comment by deviprasad135** [comment]
All the changes are related to greek names. I did not notice any other change.

**Comment by szymczdm** [comment]
The build is still failing (stable for tiny has not been updated) and now it seems there are some conflicts which will need to be fixed before this branch is ready to merge.

**Pull request merged**
