### PR TITLE
Continuous Deploy

### PR DESCRIPTION
**Pull request by Mornix**
This PR introduces a working infrastructure for [Continuous Deploy (Click this to view the current version)](https://jacquescarette.github.io/Drasil/). GitHub has a soft-limit on deploys of ten per hour. To keep things simpler, I've moved the infrastructure to only deploy on "cron" tasks from Travis. 

Out of band: You should set up a Cron job to run on `master` once per day. [Info here](https://docs.travis-ci.com/user/cron-jobs/)

### CODE REVIEW

**Comment by JacquesCarette** [comment]
Note that I can't do the cron job setup as the gh-pages branch doesn't show up as a possibility. I'm assuming that that is indeed the branch to use for that?

**Comment by JacquesCarette** [comment]
[I'm also not deleting the branch yet, for similar reasons]

**Comment by Mornix** [comment]
Branch should be `master`. `gh-pages` is the destination branch and has no Travis configuration (intended to not have Travis).

**Comment by JacquesCarette** [comment]
Indeed - done.

**Comment by JacquesCarette** [comment]
Can I delete this branch then?

**Comment by Mornix** [comment]
Yup. I still have it locally if needed.

**Pull request merged**
