### PR TITLE
Wiki: Update guide and add disclaimers to wiki files automatically

### PR DESCRIPTION
**Pull request by balacij**
Changes:
1. Updates the Contributor's Guide with information about updating the wiki.
2. Automatically adds wiki-edit disclaimers to the top of all of our `.md` files (sans `_Sidebar.md`) in the `./wiki/` folder. Further, ensures that nobody manually adds it.
3. Removes a `contributors.txt` file that I accidentally committed in #3771.
4. Uses `rsync` instead of `cp` to copy over changes (this way we can sync _deletions_ in addition to copies... we will probably need to propagate this change to #3704).

Tests:
* You can see my wiki: https://github.com/balacij/Drasil/wiki
* Latest Actions run on my repo: https://github.com/balacij/Drasil/actions/runs/9386107328/job/25845853960 -- fixed an issue regarding the grep command related to (2) that ensures nobody manually added the warnings.

### CODE REVIEW

**Comment by JacquesCarette** [comment]
So is this actually ready for review?

**Comment by balacij** [comment]
Yes :smile:

**Review by JacquesCarette — APPROVED** [review]
As far as I can tell, this is all good - but my knowledge of github workflows is not really sufficient to insure this will work!

**Review by smiths — APPROVED** [review]
@balacij I like that you made corresponding changes to the Contributor's Guide.  I like that our Contributor's Guide is now a relevant resource.  I'm optimistic that future contributors will notice the rules for editing the wiki.

**Comment by balacij** [comment]
Thanks!

Changes have already propagated, for anyone curious -- see the top of our wiki pages -- https://github.com/JacquesCarette/Drasil/wiki

**Comment by smiths** [comment]
Nice!

**Pull request merged**
