### PR TITLE
Typo. Fixes #3174

### LINKED ISSUE #3174: Typo: DblPendulum: Derivation of IM:calOfAngularAcceleration2
image

"eqaution" should be "equation"

### PR DESCRIPTION
**Pull request by JacquesCarette**
Fixes #3174 . Sort-of depends on the (later) PR #3180 , which should be merged first.

### CODE REVIEW

**Comment by JacquesCarette** [comment]
CI failed because of something with lualatex and fonts (it appears). So I've merged in the new Build.yaml, to see if that might miraculously fix it.

Otherwise we're going to have some sleuthing to figure out what changed.

**Comment by balacij** [comment]
I'm just pulling in `master` changes to see if the CI works.

**Comment by JacquesCarette** [comment]
Yep, CI worked - can either @balacij or @smiths approve, so it can be merged?

**Review by balacij — APPROVED** [review]
GH has an odd reviewal system. I can't "Approve" from the main PR page.

**Pull request merged**
