### PR TITLE
PR - Cleaning up NoPcm

### PR DESCRIPTION
**Pull request by danscime**
Minor cleanups to NoPCM which includes renaming parameters and removing descriptions from Body that are already in IMods.

### CODE REVIEW

**Comment by JacquesCarette** [comment]
build is failing.

**Comment by danscime** [comment]
@Mornix could you help me to understand the cause of the build fail?

Screen Shot 2019-05-28 at 1 13 31 PM

`Make` worked and still works on my machine in this branch, so I'm not sure.

**Comment by Mornix** [comment]
If you expand the failed section, starting on [line 811](https://travis-ci.org/JacquesCarette/Drasil/builds/538320031#L811) are build warnings which CI treats as errors.

**Comment by danscime** [comment]
Thank you @Mornix, I believe the cause of the build fail was the redundant imports in NoPCM Body.

**Pull request merged**
