### PR TITLE
Solve a second order ODE

### PR DESCRIPTION
**Pull request by cd155**
Completed solve PDcontroller in C++ and C#. Java library has a different interface to solve a second-order ODE, and it might take a longer time to complete.

In order to solve a second-order ODE, we have to reduce it to a system of first-order ODE in two equations. Therefore, this PR will complete #2906

Note: the branch name is misleading, please ignore it.

### CODE REVIEW

**Comment by cd155** [comment]
I figured out how to deal with Java in a second-order order. Since this PR hasn't been merged, I will add the Java part to this PR.

**Comment by cd155** [comment]
This PR addresses the issue in #2981

This PR did not address the issue in https://github.com/JacquesCarette/Drasil/issues/2980#issuecomment-1126542363, I added the boost library to datafiles/pdcontroller. Ideally, we don't want to have to duplicated library.

**Comment by JacquesCarette** [comment]
Boost is huge - we really don't want to have it in here twice. In fact, ideally, we wouldn't even have it once! [We would do things the same way CI does, and download it as necessary when testing]

**Comment by cd155** [comment]
Does this require to change in the make file? Any example I can check out to see how this can be done?

**Comment by JacquesCarette** [comment]
Yes, this would require a change to the make file. And the results would be hard to make portable.

I really don't want to add Boost to the Drasil repo. It's too big. Maybe @balacij has some clever ideas?

**Comment by balacij** [comment]
I agree that ideally we shouldn't/wouldn't have the entire Boost library (or any other library other than our own for that matter) placed in the repository. However, I doubt that we would want to resolve the "'required libraries management' for our generated case studies" issue on this ticket.

So, I think an alternative temporary solution is to use symbolic links. We might want to create a `datafiles/commons/` directory with all the external library packages, moved in from `datafiles/nopcm/` (which I think is where all the manually carried libraries exist), and then create [relative symbolic links](https://mokacoding.com/blog/symliks-in-git/) linking the required libraries from `datafiles/commons/...` to `datafiles/pdcontroller/...`, `datafiles/nopcm/...`. Symbolic links work really well on both Linux and macOS, but they don't exist out-of-the-box for Windows. For Windows users using Git Bash, they will need to re-install Git Bash enabling Symbolic Link support to get it working. For Windows users not using Git Bash, we will need to do a bit more research on the topic.

**Comment by smiths** [comment]
Although symbolic links shouldn't be our long term solution, I agree that a temporary solution along these lines seems reasonable.  I thought we had an existing issue about improving how we handle external libraries, but my search through the issues didn't find anything.

**Comment by cd155** [comment]
#2980 is the ticket try to address this issue. @smiths

**Comment by smiths** [comment]
Yes, #2980 is part of what I was thinking about, but I also thought there was an older issue asking for a solution that didn't involve storing any external libraries in our repo.  It is unusual for a project to keep copies of other projects.  In the long term we want to have a more elegant solution.  Maybe we can generate installers for each of the case studies, or connect with some kind of package manager?

**Comment by cd155** [comment]
Removed duplicated libraries by adding symbolic links.

**Comment by JacquesCarette** [comment]
So it's going to be tricky of me to review this - I'm going to have to do it on the commits themselves. github's interface for PRs with lots of files changed is awful and slow.

**Review by JacquesCarette — APPROVED** [review]

**Comment by cd155** [comment]
Yeah, once the chang file is over 3000, it just shows the top 3000 files.

**Pull request merged**
