### PR TITLE
Move CodeExpr to drasil-lang

### LINKED ISSUE #3307: CodeBlocks and package dependencies
In https://github.com/JacquesCarette/Drasil/commit/a6b2edef9c9bcd128796fd6848913bbafbf7bc4f#commitcomment-104797093 @tingyuw said:

> A new type CodeBlock is added in this commit. The code is not final, I'm testing but we are now able to generate code cells in the notebook after these changes (still need to address how the code will be printed). The reason why I use ModelExpr is because CodeExpr is defined in drasil-code-base, and due to package dependencies, we cannot use it in drasil-lang. What do you think would be the best approach to proceed this?

[This is better discussed in an issue than as a commit comment.]

As far as I can tell, the problem is that `drasil-code-base` contains two separate things
- `Language.Drasil.Chunk.*` which depends on drasil-database
- `Language.Drasil.Code.Expr` which does **not**.

At the moment, I think there are two routes forward that both make sense:
1. move `CodeExpr`'s defintion to `drasil-lang`
2. split `drasil-code-base` into two packages

Both of these would resolve the dependency problem. @balacij , since I think you're the last one to have committed code in `drasil-code-base`, opinions?

Personally, I think we should be looking hard at re-merging the 3 `Expr` types, so I think that all of them should be defined in the same spot. (I don't really mean 'merge', I mean to de-duplicate.)

### PR DESCRIPTION
**Pull request by tingyuw**
Closes #3307 

As discussed in #3307, this PR moves modules from `drasil-code-base` to `drasil-lang` and `drasil-code`.
@balacij Feel free to review the work if you'd like! Since you were the last person working on it, I thought you might want to take a look.

### CODE REVIEW

**Comment by balacij** [comment]
I'm happy to see `drasil-code-base` go. The `-base` was really bothering me, haha. I think there is one more reference to `code-base` in the `Makefile` that you need to remove. Otherwise, it looks good to me :smile:

**Review by JacquesCarette — APPROVED** [review]
Sorry this took so long to review, it came in at an odd time, then got buried.

Good stuff.

**Comment by JacquesCarette** [comment]
However, there is a build failure - can you fix please?

**Comment by tingyuw** [comment]
I'm not sure how to fix it. @balacij didn't experience this issue when running it locally. It might be related to issue #2209.

**Comment by balacij** [comment]
Are we able to add extra logging information around the `fromJust` to see where it's going awry?

image

**Comment by JacquesCarette** [comment]
Not easily, no. Easiest way to deal with it is to never call `fromJust` but instead use `maybe` to force dealing with `Nothing` at the use site.

**Review by JacquesCarette — APPROVED** [review]

**Pull request merged**
