### PR TITLE
added the Jmin Jmax contraints

### PR DESCRIPTION
**Pull request by muhammadaliog3**
.

### CODE REVIEW

**Comment by JacquesCarette** [comment]
You don't necessarily need to close such PRs. Here the issue is clear: your code was great but not perfect (some HLint issues) and, predictably, your changes caused things to change in the resulting documents and code, so that 'stable' needs to be updated accordingly. So you can just fix that in 1-2 more commits to this branch.

**Comment by muhammadaliog3** [comment]
@smiths whenever I try to build I get the following
```
logs/GlassBR_log.log IS NOT EMPTY -- DIFFERENCE
BETWEEN GENERATED AND STABLE OUTPUT FOUND
logs/GlassBR_log.log

diff --strip-trailing-cr -r -X ../.gitignore -x '*.txt' stable/glassbr/SRS/GlassBR_SRS.tex build/GlassBR/SRS/GlassBR_SRS.tex
38c38
< The unit system used throughout is SI (Systï¿½me International d'Unitï¿½s). In addition to the basic units, several derived units are also used. For each unit, \hyperref[Table:ToU]{Tab: ToU} lists the symbol, a description and the SI name.

 The unit system used throughout is SI (SystÃ¨me International d'UnitÃ©s). In addition to the basic units, several derived units are also used. For each unit, \hyperref[Table:ToU]{Tab: ToU} lists the symbol, a description and the SI name. 
```

Do you have guesses as to why this is happening? Does it have anything to do with UTF-8 or unicode encoding?

**Comment by bmaclach** [comment]
@muhammadaliog3 I'll jump in here because I've seen similar errors before. You are probably correct that it has to do with UTF-8. 

Some things you can try:
- Change your code page to 65001
- Change your locale `LANG` to en_US.UTF-8

Exactly how to do those things will depend on your OS and what environment you are using. If you can provide that information I may be able to help  more.

**Comment by muhammadaliog3** [comment]
Currently I am using Windows. So I went to the CMD and did ```chcp 65001```, ran ```make glassbr_diff``` in my CMD as running ```make glassbr_diff``` in git still gave me wrong encodings, got the correct encodings from CMD, updated the stable version SRS, and yet travis still does not except.

@bmaclach do you know why travis is doing this?

**Comment by JacquesCarette** [comment]
Sorry about all the noise on the commits - I have this bad habit of commenting as I review, and that sometimes leads to obsolete comments.

**Comment by smiths** [comment]
@Nathaniel-Hu, when  you work on updating the contributor's guide, please include a note about how to avoid the encoding problem encountered above.  @muhammadaliog3 should be able to help with the wording, since he solved this problem on his own machine.

**Pull request merged**
