### PR TITLE
typo fix, updated scope in body.hs of gamephy

### PR DESCRIPTION
**Pull request by oluowoj**
Files updated:

Updated typo in #1568 
Updated scope to match manual version

### CODE REVIEW

**Comment by JacquesCarette** [comment]
@Mornix hlint failed, but it looks like a script failure rather than an actual hlint problem - can you look into it please?

**Comment by oluowoj** [comment]
image

**Comment by JacquesCarette** [comment]
I'm going to close and re-open this PR, to see if the HLint failure is still there.

**Comment by Mornix** [comment]
The failing PR build looks to be related to an upstream apt mirror issue. I saw it on one of my push builds earlier today.

**Comment by JacquesCarette** [comment]
And things seem ok now, so I triggered a rebuild again.

**Pull request merged**
