### PR TITLE
Updated Citations.hs to properly reflect the title of Koothoor2013 thesis

### PR DESCRIPTION
**Pull request by harmanpreet-sagar**
Fixed Koothoor2013 reference in Citations.hs which had incorrectly stated the title of the thesis as "A document drive approach to certifying scientific computing software." This has now been fixed to include the correct title for the reference.

### CODE REVIEW

**Comment by balacij** [comment]
Nice :smile:

The CI is running right now, but if the Koothoor reference is used anywhere, it might (or should rather) error out because the [`stable` code needs to reflect these changes.](https://github.com/JacquesCarette/Drasil/wiki/Workflow#updating-stable-folder)

**Comment by smiths** [comment]
You are correct @balacij.  The CI failed because the Koothoor reference wasn't changed in stable.  @harmanpreet-sagar, you need to also commit changes to [stable](https://github.com/JacquesCarette/Drasil/tree/master/code/stable) to reflect the changes in the generated documentation.  Every pull request is verified against stable to make sure that there hasn't been any changes in the generated code.  In this case there has been a change, but it is a change that we desire.  Therefore, we need to update stable to reflect our new and improved generated documentation.

@harmanpreet-sagar, having gone through the documentation on the Drasil process, do you think there is a spot where we can reinforce the need to update stable for changes that intentionally modify the generated documentation/code to improve it?

**Comment by harmanpreet-sagar** [comment]
Thank you for the feedback! I will make changes to the stable folder now to reflect the changes. I re-read the documentation on contributing to Drasil again and realized that I might have missed the part which states the need to update the stable folder. However, I also think that reinforcing the need to update stable when changes are made that intentionally modify the generated documentation/code, would definitely aid in preventing such errors by new members. This could potentially be added under the [Workflow](https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide#workflow) section of the [Contributor's Guide](https://github.com/JacquesCarette/Drasil/wiki/Contributor's-Guide#) to better highlight this.

**Comment by smiths** [comment]
Sounds good @harmanpreet-sagar.  Thank you for your thoughtful comments on the Workflow and Contributor's Guide.  At the risk of you not volunteering your ideas in the future, I'm going to ask you to make edits to the Workflow and Contributor's Guide.  Since they are part of the Wiki we don't have the usual pull request process.  When you have made the changes, please create an issue for reviewing your changes.  If you won't be able to make the changes soon, or if they take some time to do, you should create an issue to remind yourself of the task.

**Review by JacquesCarette — APPROVED** [review]

**Comment by JacquesCarette** [comment]
There's something odd going on with respect to the Jupyter notebooks. The version that @harmanpreet-sagar pushed has a change to `attachements` that isn't on the CI version. I'm guessing there is a version mismatch that's causing this, but I'm not sure. Maybe @balacij can help investigate?

**Comment by harmanpreet-sagar** [comment]
@balacij I did open Jupyter Notebooks locally to make the necessary changes within the Jupyter Notebooks in stable. However, I only worked on the aspect where the Koothoor2013 reference was mentioned. I tried using `make stabilize` after GitHub showcased the errors for me but the command did not run for me on Bash. I also tried finding the place where the `attachments `line would have been added but I was unable to locate it.

**Comment by harmanpreet-sagar** [comment]
Maybe I was just in the wrong folder which caused my `make stabilize` command to not run. I just tried re-running it and it worked. However, it made around 324 edits to the files which I am not sure is required or not.

**Comment by balacij** [comment]
Try running make clean, followed by a make stabilize? Can you show what the changes are that worry you?

**Comment by harmanpreet-sagar** [comment]
It still shows around 324 changes. Maybe it is just the sheer amount of changes that worry me. Should I create a new branch through which I push these changes so that u can see or should I just push them into my old branch itself?

**Comment by balacij** [comment]
Either way is fine with me, no worries :)

**Comment by harmanpreet-sagar** [comment]
You can access the changes made by make stabilize [here](https://github.com/JacquesCarette/Drasil/tree/3319-make-stabilize-issues-fix-koothoor2013-reference).

**Comment by balacij** [comment]
Wow, that's really odd! It's renaming all the files, double nesting them in excessive folders. I've never seen this before.

We'll need to take a look at the Makefile and your development environment.

**Comment by harmanpreet-sagar** [comment]
Oh ok. How do you suggest I can show you my makefile and my development environment?

**Comment by balacij** [comment]
The `Makefile` is shared on git, so we all have the same copy, it's in the `code/` directory :smile: You'll need to have a look at this section to see where it's going awry. When you run the `make stabilize` (or `make swhs_stabilize`, etc.), you should see the commands that the Makefile actually runs, and they should be of the form shown in this snippet:

https://github.com/JacquesCarette/Drasil/blob/c1d77dcee843cbcb5caaeaa57f5da65bab95d2df/code/Makefile#L305-L310

Regarding the information, just some basic information about your setup would be good (OS, terminal, shell).

**Comment by balacij** [comment]
By the way, in the meantime, you can manually copy and paste the `build/` folder over the `stable/` folder using `cp` so that we can get this PR pushed through, and you can figure out what's wrong with your `make stabilize` runs on the side.

**Comment by harmanpreet-sagar** [comment]
Ok yes, I will copy the build folder now and will get this PR pushed first.

**Comment by harmanpreet-sagar** [comment]
The PR has now been modified to include changes to the markdown of the Jupyter Notebooks that were initially preventing Drasil from compiling. The code has now passed the GitHub tests. Kindly let me know if I am good to close this issue now.

**Pull request merged**
