### PR TITLE
GlassBR_SRS_RemoveScopeProject

### PR DESCRIPTION
**Pull request by vajihehm**

### CODE REVIEW

**Comment by smiths** [comment]
@JacquesCarette, I did ask @vajihehm to remove the use cases.  GlassBR is the only example that has uses cases and they are completely devoid of information.  However, we still want to keep the scope of the project.  @vajihehm, you haven't deleted the scope of the project, correct?

**Comment by vajihehm** [comment]
@smiths as @JacquesCarette  mentioned 'scope of the project' has been removed, I am working on it and I will commit soon. Thanks.

**Comment by vajihehm** [comment]
@smiths Just to confirm. I double checked your comments in manual SRS as well as template, according to that this section is not part of template you asked me remove the section. So, do you ask me to add this section yet? I have attached your comments in glassbr_srs and Template SRS.
[SRS.pdf](https://github.com/JacquesCarette/Drasil/files/2897344/SRS.pdf)
scopecomments

**Comment by smiths** [comment]
You are correct @vajihehm.  I was thinking of the Scope of Requirements section.  There is no section in the SRS template for "Scope of Project."  You can go ahead and remove the entire "Scope of Project" section from the SRS.  I apologize for the confusion.

**Comment by vajihehm** [comment]
> You are correct @vajihehm. I was thinking of the Scope of Requirements section. There is no section in the SRS template for "Scope of Project." You can go ahead and remove the entire "Scope of Project" section from the SRS. I apologize for the confusion.

Thanks! Done.

**Pull request merged**
