### PR TITLE
Add date to Doxygen comments

### LINKED ISSUE #1782: Add date to doxygen comments for modules
The module-level doxygen comments in generated code could be enhanced with a date field. There are Haskell libraries that can be used to get the current date (http://hackage.haskell.org/package/time-1.9.3/docs/Data-Time-Calendar.html and http://hackage.haskell.org/package/time-1.9.3/docs/Data-Time-Clock.html). The date will likely need to be requested within the `genCode` function because it is an IO action, and then passed along to the generator from there.

### PR DESCRIPTION
**Pull request by bmaclach**
This PR closes #1782 by adding a date field to the module-level doxygen comments.

#1793  should be merged first.

### CODE REVIEW

**Comment by Mornix** [comment]
Dates enabled for the examples in stable will cause many issues when diffing after today's date (August 7th) with the current changes to stable.

**Comment by bmaclach** [comment]
@Mornix Good point. I can't independently turn off the dates without turning off the module-level comments altogether... but I could add an additional `Choice` for turning dates on/off. Should I do that @JacquesCarette @smiths? Or any other ideas?

**Comment by smiths** [comment]
@bmaclach, I like the addition of dates to the comments, but @Mornix is right about the problem with our diffs.  Your solution of a choice for turning the dates off sounds good to me.

**Comment by bmaclach** [comment]
Added the choice and turned off dates for our examples.

**Comment by JacquesCarette** [comment]
Needs a master merge, but otherwise ready to go.

**Pull request merged**
