### PR TITLE
Revert "Revert "resolving conflicts""

### LINKED ISSUE #2786: Making all example files lowercase + removing cabal files
Looks like master went back to using capitals in the example folders and didn't remove all the cabal files.

### PR DESCRIPTION
**Pull request by balacij**
Closes #2786 
Resolves discussion on #2735 

This reverts commit 720bd4b9a86d6d2d38f8ab444a883ad6eadafad0.

### CODE REVIEW

**Comment by balacij** [comment]
Just going to double check the PRs that were merged in later, to make sure this doesn't affect them, but I _think_ this should fix master's reversion of a few PRs.

**Review by JacquesCarette — APPROVED** [review]

**Comment by JacquesCarette** [comment]
Unfortunately, the build failed...

**Comment by balacij** [comment]
Yep, it looks like it's just the Haddock docs. I think we can create a brute force PR to resolve it here, and then have them properly resolved via #2766 + #2784

**Review by JacquesCarette — APPROVED** [review]

**Comment by JacquesCarette** [comment]
build worked, so merged it right away.

**Comment by balacij** [comment]
Nice!

**Pull request merged**
