### PR TITLE
Website update

### PR DESCRIPTION
**Pull request by peter-michalski**
Updates for  #3039

### CODE REVIEW

**Comment by smiths** [comment]
@peter-michalski, what is the best way to review these changes.  I've clicked around through the code, but it would be nice to see the web-page itself, rather than the code that generates it.  Is there a way to generate the web-page from this branch to look at it?

**Comment by peter-michalski** [comment]
> Is there a way to generate the web-page from this branch to look at it?

You will need to clone my repo, go into the branch and `make website`. The HTML file will be in Drasil/code/Website/HTML/

**Review by smiths — APPROVED** [review]
I approve of the new webpage, but I'll leave it to @JacquesCarette to determine if the webpage is ready to be merged.

**Comment by peter-michalski** [comment]
> By the way, why are you using a fork instead of a branch? Is it something to do with building the webpage?

No, just out of habit I work in forked repos when I am not an owner or frequent developer. I started working with Drasil in the same mindset, but now that you mention it, it might be a good idea to go ahead and branch the main repo when working on future issues.

**Comment by JacquesCarette** [comment]
Yes, we definitely want you to become a "frequent developer" of Drasil! (Review of this incoming)

**Review by JacquesCarette — APPROVED** [review]
As far as improving the website, this achieves that aim, in a way that's completely consistent with what is already here - thus the approval.

A deeper look at the code reveals all sorts of opportunities for further improvement. But it doesn't make sense to hold up these improvements for that, but make them another round.

**Comment by balacij** [comment]
The new website looks great! :smile:

**Pull request merged**
