### PR TITLE
More do notation throughout GOOL

### PR DESCRIPTION
**Pull request by bmaclach**
As discussed at the April 29th GOOL code review meeting, this PR passes over GOOL and uses do-notation instead of long, unreadable lines.

### CODE REVIEW

**Comment by JacquesCarette** [comment]
Also, there might be linting issues, CI is not happy.

**Comment by bmaclach** [comment]
Linted and addressed your comments in the latest batch of commits.

**Comment by JacquesCarette** [comment]
lint still throwing errors. Sophisticated ones now.

**Comment by bmaclach** [comment]
Ok, build finally passed.

**Pull request merged**
