### PR TITLE
Renamed UncertainChunk to Uncertain

### PR DESCRIPTION
**Pull request by NoahCardoso**
I renamed the UncertainChunk datatype to just Uncertain as part of the renaming chunks named in the form "XChunk" as just "X".
Contributes to #3244

### CODE REVIEW

**Comment by samm82** [comment]
Based on @JacquesCarette's [comment](https://github.com/JacquesCarette/Drasil/issues/3244#issuecomment-1404049326), since "Uncertain" is also an adjective, we may want to think of another name for these chunks as well. Perhaps investigating the difference between `UncertainChunk` and `UncertQ` would help shed some light on this!

**Comment by NoahCardoso** [comment]
@samm82 would changing UncertainChunk to Uncertainty be better? Also do you want all of the Chunks to be nouns?

**Comment by JacquesCarette** [comment]
Now is our opportunity to think a bit deeper: `UncertainChunk` is the encoding of a `ConstrainedChunk` that *add*s an uncertainty field to it. It isn't "an uncertainty".

The problem with coming up with a good name for it is that it is likely to require coming up with a new better name for `ConstrainedChunk` first!

So there's a bigger issue (which you should probably get @samm82 and @balacij help you draft) about naming all things derived from Quantity.

**Comment by NoahCardoso** [comment]
This pr is no longer relevant and should be deleted

**Pull request closed without merging**
