### PR TITLE
Remove capitalization from concepts in PDController #3534

### PR DESCRIPTION
**Pull request by daijingz**
My modification after using the GitHub desktop
Here I only use make, make clean, and make stabilize three commands.
This time I have used an extra command: stack exec pdcontroller, so there are some extra files created and they are uploaded as well. (e.g., [code/SRS/HTML/PDController_SRS.html](https://github.com/JacquesCarette/Drasil/compare/master...daijingz:Drasil:master?expand=1#diff-b393feabd1761b9512b6c86b68baedd7f9b1e869407924198d9ae9bba572891e))
Now it is "stabilized", at least it works at machine, I need help about submitting my modified version from my local machine

### CODE REVIEW

**Comment by daijingz** [comment]
I do not know whether I should upload these files, since I know they are documentations

**Comment by smiths** [comment]
@daijingz it looks like you are making progress.  :smile:  The diffs for the files in stable look good.  However, you have added some files to the code folder that should be added.  Specifically, there are some generated files in a folder called SRS that shouldn't be in the pull request, like the [html version of the requirements for PD Controller](https://github.com/JacquesCarette/Drasil/pull/3651/files#diff-7a2ff9bbf917022cdd9b5b6910ed752775e7435eda9b9250a507cbf5a60bafea).   Please remove the folder `code\SRS` from your pull request.  (You don't need to close this pull request.)

**Comment by daijingz** [comment]
There is an easy question: how to remove some files in the submission?

**Comment by daijingz** [comment]
Ok so i remove all changed files in the code/SRS

**Comment by smiths** [comment]
@daijingz the files are still in the pull request.  You can see them by clicking on the Files Changed tab.

**Comment by daijingz** [comment]
Now it is done, can everyone see these changes?
Simultaneously, do we have other problems?

**Review by smiths — APPROVED** [review]
The extra files are now gone!  I approve the changes to stable, but changes to the code need to be approved by @JacquesCarette.

**Pull request merged**
