### PR TITLE
Update DblPend's IM outputs to be theta instead of alpha

### PR DESCRIPTION
**Pull request by samm82**
Based on the discussion on #3533, I updated the outputs of DblPend's IMs to output the thetas themselves, since that is what is currently desired from them.

image

### CODE REVIEW

**Comment by samm82** [comment]
I also update the relevant FRs (note that the output one will soon be generated in table form):

image

After #3600, we could also output the alphas fairly trivially (depending on how it would affect the code generation).

**Review by JacquesCarette — APPROVED** [review]
Code changes make sense to me. Might be worth merging in master so that no .json leaks in.

**Review by smiths — APPROVED** [review]
The changes look good to me.  I'm assuming that these changes don't break the code generator, since there are no code changes for stable listed.

There are some odd things that I happened to notice in the generated code, like in the html code the symbol for omega is different between the equation and the list in the description.  The order of L_1 and L_2 are opposite to what would be expected in the description field.  These are things we can fix in the future.

**Comment by smiths** [comment]
It looks like the json files have leaked in!

**Review by cd155 — APPROVED** [review]

**Review by JacquesCarette — APPROVED** [review]

**Pull request merged**
