### PR TITLE
Add UC to Tables of Acronyms and Abbreviations

### PR DESCRIPTION
**Pull request by niazim3**
Fixed issue in the comments of smiths/caseStudies#100, and updated stable in all examples.

### CODE REVIEW

**Comment by niazim3** [comment]
Should the table of abbreviations be automated like the table of symbols currently are? So that we won't have extra abbreviations or missing ones in the table and wouldn't need to make manual changes such as these... @szymczdm

**Comment by szymczdm** [comment]
Ideally, yes. I believe @halonazhao's work with parsing the document for units, symbols, and whatnot could also be applied to the acronyms (though it might be a bit tricky), so that's definitely something to keep in mind going forward.

**Comment by niazim3** [comment]
Should an issue be made for that then? I don't currently see any in relation to acronym/abbreviation extraction from the doucment...

**Comment by szymczdm** [comment]
@niazim3 yes, an issue would be a great idea. Could you please create one? I think using the `enhancement` tag would also be appropriate.

**Comment by niazim3** [comment]
Issue made; assigned @halonazhao for now; if anyone else should be assigned please let me know.

**Pull request merged**
