### PR TITLE
Adding more Set Opertions in GOOL

### PR DESCRIPTION
**Pull request by NoahCardoso**
This pr adds `setAdd`, `setRemove` and `setUnion` to GOOL but I did not have time to finish set union in C++ but I don't think it would be too hard to do.

### CODE REVIEW

**Comment by B-rando1** [comment]
It might be helpful to rebase on #3942 so that you can add the new functions to Julia with that implementation in mind.

**Review by JacquesCarette — APPROVED** [review]
Very nice! Good team work, and nice effectiveness (i.e. you implemented new features very quickly).

**Review by JacquesCarette — APPROVED** [review]

**Comment by JacquesCarette** [comment]
Serves me right for approving before the build finished... And I've just done it again.

**Comment by B-rando1** [comment]
Note also that `setUnion` is not implemented in C++ yet.

**Review by JacquesCarette — APPROVED** [review]

**Pull request merged**
