### PR TITLE
Swhs datadefs

### LINKED ISSUE #1070: SWHS: Difference b/w Stable and Manual: Add definitions for tau_P^S and tau_P^L
Issue #1069 highlighted that tau_P^S and tau_P^L need to be added as data definitions.  This was done in the manual version at:

https://github.com/smiths/swhs/commit/6bf8ec052868e7a90d803a75b5dfcef1d48c9f3a

These changes need to be propagated to stable (Drasil)

### PR DESCRIPTION
**Pull request by danscime**
Added tau_P^S and tau_P^L to SWHS data definitions.
This should close #1070

### CODE REVIEW

**Comment by JacquesCarette** [comment]
And because of other merges, this is now conflicting - can you fix this please?

**Comment by danscime** [comment]
Fixed conflict.

**Comment by danscime** [comment]
Did not mean  to add code/SRS and code/Website, they have been removed with either this pull request, or in #1257.

**Comment by JacquesCarette** [comment]
And another merge is required...

**Comment by danscime** [comment]
Resolved Merge.

**Comment by JacquesCarette** [comment]
But now Travis fails... note that this PR now only contains changes to stable and nothing else, which is weird.

**Comment by danscime** [comment]
What should be done?

**Comment by danscime** [comment]
These changes have actually been added in #1257.
My Latex Tab branch was created as if the SWHS changes had been made, I may have branched from my branch.
In which case, this PR should not go through?

**Comment by JacquesCarette** [comment]
You should click on 'Details' on the page on github for this PR to see how/why the build failed. If you can't figure out the problem, maybe get some help from @Mornix or @bmaclach ?

**Comment by danscime** [comment]
The checks failed due to a mismatch between generated and stable.
Regardless, the changes from this PR were already added in #1257.
I think we can just close this PR, no merge needed.

**Pull request closed without merging**
