### PR TITLE
 Spell check and taking out empty lines between imports

### PR DESCRIPTION
**Pull request by Awurama-N**
closes Issue #2393

### CODE REVIEW

**Comment by balacij** [comment]
I think we're making an edit to the generated artifacts here, so I think we need to also edit the `code/stable/` folder to reflect these changes too, otherwise the build actions will fail.

**Comment by Awurama-N** [comment]
oh okay, i'll go in and make those changes 
Thank you

**Comment by Awurama-N** [comment]
do i have to change all instances of the words? and in other files as well? 
or it was a different file in stable

**Comment by balacij** [comment]
The [logs](https://github.com/JacquesCarette/Drasil/pull/2408/checks?check_run_id=2547431496) will show you all areas that are currently problematic, specifically you might want to look for lines saying `diff --strip-trailing-cr -r -X ../.gitignore -x '*.txt' stable/<SomeFile> build/<SomeFile>` for seeing which files are currently different (note that the stable will be pointed left `<` and the "current build" will be pointed right with a `>`). You can probably also copy and paste your build files over the stable files to overwrite all changes. Just make sure you're only altering the files that are already tracked however.

**Comment by smiths** [comment]
@Awurama-N, can you please add the instructions for updating stable (as described by @balacij) to the contributor's guide.  We don't currently say anything about these details there and I'm sure it will be helpful for future contributors.

**Comment by Awurama-N** [comment]
Okay I'll assign that to myself and get it done

**Comment by JacquesCarette** [comment]
Right - one of the things we **don't** do is edit stable "by hand". We look at the differences (diffs) by hand, and then once they appear to be acceptable, we simply copy the build files over to stable.

**Comment by JacquesCarette** [comment]
Also, you'll have to do a merge from master first, because there's a conflict currently.

**Comment by balacij** [comment]
@Awurama-N If you're interested, you don't need to restart this entirely, you can perform the merge conflict fixes locally and then recommit the patched work. For example, you can locally run:

```
git fetch
```
( to update repo information using `origin` )

```
git pull origin master
```
( to start the merge of `master` onto your branch )

Afterwards, it will tell you that there are some conflicts that need to be resolved, listing which files need to be fixed. In those files, you'll see some areas that have `>>>>>>>>>>>>>>>>` and `<<<<<<<<<<<<<<` (and the likes) that you will need to decide which one to use (or how to merge them). You can check out the [GitHub docs](https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/resolving-a-merge-conflict-using-the-command-line#competing-line-change-merge-conflicts) for some really good information about this too.

**Pull request closed without merging**
