### PR TITLE
Automating References

### PR DESCRIPTION
**Pull request by Ant13731**
Contributes #2675 
I only ran into one weird thing: In GlassBR, I had to manually add the citations `astm2009` and `astm2016` to the reference database. I couldn't figure out why the citation database wasn't automatically including them, so I think it's best to make a new issue for it. Other than that, a lot of the manual referencing overhead from the examples has been removed.

### CODE REVIEW

**Comment by JacquesCarette** [comment]
Need a master merge.

**Review by JacquesCarette — APPROVED** [review]
This is the kind of PR that I love - 0 changes to stable, but hundreds of lines of code deleted and the API of many modules many smaller.

**Comment by JacquesCarette** [comment]
My guess about GlassBR: the only place those 2 references are used might be quite 'deep', and your checking doesn't quite dig into that part? A new issue is indeed fine.

**Comment by Ant13731** [comment]
I think I found the source of the error: `codeSpec` was using the system information before the "fill" functions were called. Replacing `si` with `fullSI` seems to work.

**Review by JacquesCarette — APPROVED** [review]

**Pull request merged**
