### PR TITLE
Create new doc folder + Add Contributor's Test & Answers

### LINKED ISSUE #2161: Contributor Test
Now that you have almost completed #2136, the next task is to write a test for future contributors.  @JacquesCarette and I discussed approaches for training future developers and the idea we came up with was to start with a test.  @Nathaniel-Hu, please write a short test, consisting of multiple choice and short answer questions.  We'll use this test for future developers.

The test will be easier to write, and easier for @JacquesCarette and I to judge, if you include the answers.  You can create a branch for the test.  When we are done, we'll probably delete the branch, so that the answers aren't available for future developers.  :smile:

I'll attach LaTeX files that you can use as a starting point.  The files are from a previous undergrad test.  I haven't done anything to change the test to suit our current needs; I just deleted most of the questions.  You can remove most of the preamble.  We just need a title for the test.  (We could do the test with other software, but practicing with LaTeX would be useful (and fun!) for you.)

You will have to rename the first file to have the extension tex, and the second file to have the extension cls.  GitHub doesn't support those extensions, so I relabelled both files to have the extension txt.  :smile:

[PotentialContributorTest.txt](https://github.com/JacquesCarette/Drasil/files/4724969/PotentialContributorTest.txt)

[examtst.txt](https://github.com/JacquesCarette/Drasil/files/4724974/examtst.txt)

### PR DESCRIPTION
**Pull request by Nathaniel-Hu**
- contains a new `doc` folder in the main Drasil folder, with 4 new files
   - new files include ContributorTestAnswers.tex, examtst.cls, ContributorTest.pdf and ContributorTestAnswers.pdf
   - main file of interest is ContributorTestAnswers.tex; Contributor's Test intended to gauge new contributor's understanding of git and other Drasil related topics
   - ContributorTest.pdf and ContributorTestAnswers.pdf are the rendered PDF files of the test + answers
   - examtst.cls is a support file for rendering the PDF files from ContributorTestAnswers.tex

- also includes changes to README.md file
   - Summary of Folder Structure and File Contents section updated to include new entry for `doc` folder

- closes #2161; related to Issue #2171

### CODE REVIEW

**Comment by smiths** [comment]
@Nathaniel-Hu, why do you have the old test in the PR?  It seems to me that we can just have the last version of the test in the repo.  I think it will be confusing for people in the future that look at the test and wonder why there are two versions.

**Comment by Nathaniel-Hu** [comment]
Ok then, I will remove the old versions. Do I need to include the PDF rendered version of the test too, or no?

**Comment by smiths** [comment]
I suggest you include two pdf versions of the test - one with answers and one without.  You can generate the different versions from your test tex file.

**Comment by JacquesCarette** [comment]
I tend to not put generated things in repos. The main exceptions are: 1) ease of use, 2) snapshot of an official submission.

For this case, I think ease of use warrants putting them in.

**Comment by Nathaniel-Hu** [comment]
Alright then. I will create two pdf versions; one with answers, and one without, and include them in the Contributor's Test folder.

**Comment by Nathaniel-Hu** [comment]
@smiths and @JacquesCarette, should the examtst.cls file also be included here, or should that be excluded?

**Comment by smiths** [comment]
I think you should include the `examtst.cls` file.  For the same reason that @JacquesCarette mentioned that you usually don't put pdf files under version control, but in this particular case we will make an exception.  The "right" way to do this would be to have a folder of tex resources that we reuse, or a pointer to the maintained repo where the tex resources are located.  This just isn't worth the effort though.  We want future students to be able to compile the tex file, and they'll need `examtst.cls` to do that.

**Comment by Nathaniel-Hu** [comment]
Alright then. Is this pull request cleared to be merged into master then?

**Pull request merged**
