### PR TITLE
Adding sections to SRS template

### PR DESCRIPTION
**Pull request by oluowoj**
Trying to see how I can add all the sections (empty) to the SRS. I was able to pull in some of the sections without dependencies, using Body.hs with some imports. The rest of the sections have dependencies and I want to see how I can create those in the SRS as well.

### CODE REVIEW

**Comment by oluowoj** [comment]
@JacquesCarette i think you mentioned a while ago that I could check on my machine if a build will pass CI build or not. Can you please point me to the app to use for the check?

**Comment by oluowoj** [comment]
@JacquesCarette, I started adding comments to Body.hs  as per your comment in PR #2223

**Comment by JacquesCarette** [comment]
The tests already run with 'make'. You can install and run hlint locally. That should catch the majority of the problems.

But if you want to go all out, there's https://github.com/nektos/act. I have not yet tried it.

**Comment by oluowoj** [comment]
> This is a good start. Do you want me to merge this in now, and you'll do more PRs as you continue to improve this?

Yes, please

**Comment by oluowoj** [comment]
> The tests already run with 'make'. You can install and run hlint locally. That should catch the majority of the problems.
> 
> But if you want to go all out, there's https://github.com/nektos/act. I have not yet tried it.

Thank you, I will try it.

**Pull request merged**
