### PR TITLE
Gamephy srs

### PR DESCRIPTION
**Pull request by oluowoj**
Added new Data Definition "Torque"
I think I need a new symbol r?
r : is a position vector of the point where the force is applied, measured from the axis of rotation. I used another symbol "r_OB" for now.

### CODE REVIEW

**Comment by smiths** [comment]
@oluowoj, if there are questions about the best way to present the physics, we should probably have those discussions with the manual case study.  In the interest of separation of concerns, we can sort out the best way to present the physics in the manual version and then just focus on the translation to Drasil for the Drasil version.

**Comment by oluowoj** [comment]
sure, I will talk to you this afternoon in your office.

**Comment by JacquesCarette** [comment]
I approved the changes 'visually', but now I see that the changes actually cause printing differences.  Please deal with these (and add a commit) to fix the CI build.

**Comment by JacquesCarette** [comment]
Note that the builds are still failing.  Do they somehow work on your machine? It would be nice to merge this, but I can't until the builds are clean.

**Comment by oluowoj** [comment]
The build works perfectly fine on my machine and I copied the .html and .tex file into stable folder but still no luck.

**Comment by JacquesCarette** [comment]
Try merging `master` into your branch. That should also update the CI scripts, which should let you see what went wrong (Gabe improved some of the scripts).
Please do not do multiple pieces of work in the same branch / PR. I think that change f6023b0 is not related to the rest?  If so, it should be done as a separate PR, from a separate branch.

**Comment by JacquesCarette** [comment]
Weirdly, it looks like the build completed fine, but didn't get picked up? I'll merge in.

**Comment by oluowoj** [comment]
thanks,

**Pull request merged**
