### PR TITLE
#3581 HasDerivation should be called MayHaveDerivation

### LINKED ISSUE #3581: `HasDerivation` should be called `MayHaveDerivation`
The class `HasDerivation` actually only gives you a `Maybe Derivation`.
```haskell
class HasDerivation c where
  derivations :: Lens' c (Maybe Derivation)
```

### PR DESCRIPTION
**Pull request by daijingz**
Closes #3581

### CODE REVIEW

**Review by balacij — APPROVED** [review]
Thank you for splitting the PR, @daijingz, sorry for the troubles!

**Comment by daijingz** [comment]
@balacij Should I update the second part just now? I still feel updating the second part may have troubles and possible risks. Let me wait until this PR is merged.

**Comment by balacij** [comment]
There's no need to add that extra work here. On your fork, you can open up a branch off of your `master` branch and then use that branch to open up a new PR to this repo. I can try to get you started, but it would be good to familiarize yourself with git.

You can open up a new branch with `git checkout -b newBranchName`, then you can work on it as normally, commit your changes, push them up to your repository, and then open up a PR (on GitHub) from the new branch over to this 'main' repository.

**Comment by daijingz** [comment]
> There's no need to add that extra work here. On your fork, you can open up a branch off of your `master` branch and then use that branch to open up a new PR to this repo. I can try to get you started, but it would be good to familiarize yourself with git.
> 
> You can open up a new branch with `git checkout -b newBranchName`, then you can work on it as normally, commit your changes, push them up to your repository, and then open up a PR (on GitHub) from the new branch over to this 'main' repository.

I am quite unfamiliar with this branch, but I am doing it. Because I found only one fork is available, Drasil can only have one copy in my remote repos. I have two branches in my git desktop.
1MYXAP~2XL9EGU9 FQ41{(D

**Comment by balacij** [comment]
You might be interested in the [Git2Know](https://github.com/JacquesCarette/Drasil/wiki/Git2Know-for-Drasil) wiki page, specifically the [Pull Requests](https://github.com/JacquesCarette/Drasil/wiki/Git2Know-for-Drasil#pull-requests) section. There is also the [Workflow](https://github.com/JacquesCarette/Drasil/wiki/Workflow) page.

I have no experience with the GitHub desktop application, so I can't definitively explain why it shows 2 Drasils on the LHS. I imagine it's showing 2 copies because you have 2 copies of it cloned on your machine? Or maybe alternative remotes? Regardless, I can help you if you go with git from the terminal (which generally has a lot of public resources available on it). Git as a Version Control System (VCS) is pretty standard nowadays, so it might be good for you to familiarize yourself with it in general (not just for Drasil, but for work). Atlassian (a competitor to GitHub) has numerous tutorials related to [Git](https://www.atlassian.com/git/glossary#commands), and a broader discussion on [VCS](https://www.atlassian.com/git/tutorials/what-is-version-control).

**Comment by daijingz** [comment]
> You might be interested in the [Git2Know](https://github.com/JacquesCarette/Drasil/wiki/Git2Know-for-Drasil) wiki page, specifically the [Pull Requests](https://github.com/JacquesCarette/Drasil/wiki/Git2Know-for-Drasil#pull-requests) section. There is also the [Workflow](https://github.com/JacquesCarette/Drasil/wiki/Workflow) page.
> 
> I have no experience with the GitHub desktop application, so I can't definitively explain why it shows 2 Drasils on the LHS. I imagine it's showing 2 copies because you have 2 copies of it cloned on your machine? Or maybe alternative remotes? Regardless, I can help you if you go with git from the terminal (which generally has a lot of public resources available on it). Git as a Version Control System (VCS) is pretty standard nowadays, so it might be good for you to familiarize yourself with it in general (not just for Drasil, but for work). Atlassian (a competitor to GitHub) has numerous tutorials related to [Git](https://www.atlassian.com/git/glossary#commands), and a broader discussion on [VCS](https://www.atlassian.com/git/tutorials/what-is-version-control).

This is because I built two different branches via the GitHub desktop. They have same part of files.

Now I feel afraid of using git code because some of its effects are unobservable, and before I have some confusions. (That is why I feel GitHub desktop is a convenient tool since it displays everything.)
@balacij You mentioned the command "git checkout -b newBranchName", can you give me an example of the parameter "newBranchName"? Let me try.

**Review by JacquesCarette — APPROVED** [review]

**Pull request merged**
