### PR TITLE
Change type-checking expectation for DifferentialModel

### PR DESCRIPTION
**Pull request by balacij**
Related to #3104 

I might as well commit it, I'm not entirely sure if it's right yet, but I think it makes more sense.

### CODE REVIEW

**Comment by JacquesCarette** [comment]
I'll take care of fixing this (the build failed with an hlint warning)

**Comment by balacij** [comment]
Ah, thank you very much!

**Comment by JacquesCarette** [comment]
So now the error is
```
`imPDRC` exposes ill-typed expressions!
  - ERROR: Inferred type `Vect Real` does not match expected type `Real`
  - ERROR: Inferred type `Vect Real` does not match expected type `Real`
```
Problem is, I have no idea where this inferred type comes from. As far as I can tell, there are no vector operations involved, and that seems to be the only way `Vect` gets inferred.

**Comment by JacquesCarette** [comment]
Aha, a clue: `formEquations`, which is used to create what is actually checked, uses `idx`. So it assumes some things are vectors, when this is not actually a good assumption. So it looks like it is `formEquations` which has a problem.

**Review by JacquesCarette — APPROVED** [review]

**Comment by JacquesCarette** [comment]
So I'm going to merge this in, even though it's only a partial fix. But this is definitely better.

**Pull request merged**
