### PR TITLE
Makefile Variables

### LINKED ISSUE #1298: Generated C# Makefile does not work on Windows
I get the following error when running `make` for the generated C# GlassBR code:
```
mcs Control.cs InputParameters.cs DerivedValues.cs InputConstraints.cs OutputFormat.cs Calculations.cs ReadTable.cs InputFormat.cs Interpolation.cs -out:GlassBR.exe
process_begin: CreateProcess(NULL, mcs Control.cs InputParameters.cs DerivedValues.cs InputConstraints.cs OutputFormat.cs Calculations.cs ReadTable.cs InputFormat.cs Interpolation.cs -out:GlassBR.exe, ...) failed.
make (e=2): The system cannot find the file specified.
make: *** [GlassBR.exe] Error 2
```
The error seems to be because `mcs` is being used to compile the code instead of `csc`.

### PR DESCRIPTION
**Pull request by Mornix**
This PR introduces a (more) dynamic form of Makefile variables. Gone are the days of hardcoding `"$(VAR)"` places. Makefiles no longer contain variables which aren't used, and don't print the OS preamble if not needed. 

This PR also addresses #1298 by added an OS variable for a default C# compiler based on platform. I've added @bmaclach as a reviewer to ensure `csc` works as expected in the `Makefile` on Windows.

Closes #1298

### CODE REVIEW

**Comment by bmaclach** [comment]
@Mornix I get this error now with the C# makefile:
```
$ make
csc Control.cs InputParameters.cs DerivedValues.cs InputConstraints.cs OutputFormat.cs Calculations.cs ReadTable.cs InputFormat.cs Interpolation.cs -out:GlassBR.exe
Microsoft (R) Visual C# 2008 Compiler version 3.5.30729.9034
for Microsoft (R) .NET Framework version 3.5
Copyright (C) Microsoft Corporation. All rights reserved.

fatal error CS2022: Options '/out' and '/target' must appear before source file names
make: *** [GlassBR.exe] Error 1
```

I tried manually changing the makefile to move -out before the file names, like so:
```
GlassBR$(TARGET_EXTENSION): Control.cs InputParameters.cs DerivedValues.cs InputConstraints.cs OutputFormat.cs Calculations.cs ReadTable.cs InputFormat.cs Interpolation.cs
	$(CSC) -out:GlassBR$(TARGET_EXTENSION) Control.cs InputParameters.cs DerivedValues.cs InputConstraints.cs OutputFormat.cs Calculations.cs ReadTable.cs InputFormat.cs Interpolation.cs
```

And then it worked. But hopefully that wouldn't break it for other OSs?

**Comment by JacquesCarette** [comment]
So I guess I'll hold off on the merge then... (plus there's a conflict).

**Comment by Mornix** [comment]
Both issues should be resolved.

**Comment by bmaclach** [comment]
Can confirm the makefile issue was fixed!

**Comment by JacquesCarette** [comment]
Sorry, because I waited, there's now a conflict...

**Pull request merged**
