### PR TITLE
Adding Precision Capabilities

### LINKED ISSUE #1258: Specifying Precision
Work on branch `precision`

As mentioned in (#868), we need a way to specify precision of uncertainties (and other values?). I think the best approach would be to create a new type `Uncertainty` that takes a `Double` (uncertainty) and `Maybe Integer` (precision).

# TODO
- [ ] Move definition of `Uncertainty` to `Uncertainty.Core`
- [ ] Improve helper functions as per comment on f6c27135526836bb30e831439dba8b870cf9a739

### PR DESCRIPTION
**Pull request by samm82**
Added the ability to specify a precision for uncertainties, which will close #1258.

### CODE REVIEW

**Comment by samm82** [comment]
If I still have work to do on this branch, should I close the PR and re-open it when I'm ready? @JacquesCarette

**Comment by JacquesCarette** [comment]
Yes.

**Comment by samm82** [comment]
@JacquesCarette I've made the fix - there are now two accessors, `uncVal` and `uncPrec` to get the fields of the `Uncertainty` returned by the `Lens` from `HasUncertainty`.

**Comment by samm82** [comment]
Closing until I improve the helper functions

**Comment by samm82** [comment]
I think I've got it now

**Pull request merged**
