### PR TITLE
SSP Properties of Correct Solution

### PR DESCRIPTION
**Pull request by samm82**
Added placeholder Properties of Correct Solution for SSP example with reference from the `Correct` NFR.

### CODE REVIEW

**Comment by JacquesCarette** [comment]
At this point, this seems ok to me.  Should I merge it in?

**Comment by samm82** [comment]
Sounds good to me!

**Comment by JacquesCarette** [comment]
and another merge is needed!

**Comment by samm82** [comment]
Done! @JacquesCarette

**Comment by JacquesCarette** [comment]
And in the meantime, SSP changed again!

**Comment by samm82** [comment]
Merge it quick before it conflicts again! 😂

**Comment by JacquesCarette** [comment]
I wasn't necessarily 'quick', but I did make sure to merge this one *next* so that it doesn't conflict again!

**Pull request merged**
