### PR TITLE
capitalized pendulum in the introduction

### LINKED ISSUE #2615: Update Introduction for Double Pendulum
The introduction for Double Pendulum does not follow the pattern of the other examples.  Please make the following changes:

- Please modify the wording so that the Pendulum is capitalized in the last word of the first paragraph.
- The introduction says that the purpose will be presented, along with other parts that are not included.  We should add those other parts to the document.  If adding the other parts is a significant amount of work @cd155, please create issues for each subsection.

### PR DESCRIPTION
**Pull request by cd155**
- The Pendulum is capitalized in the last word of the first paragraph.

- I created additional three tickets to add three new sections.

close #2615

### CODE REVIEW

**Review by smiths — CHANGES_REQUESTED** [review]
@cd155, when you make changes that cause changes in the generated code, you need to also commit the corresponding changing in the generated code.  We put the correct generated code in the stable folder.  The build process checks that any changes generate the "correct" code.  If we change our opinion on what is correct, then we need to update stable to reflect this change.

**Review by JacquesCarette — APPROVED** [review]

**Comment by JacquesCarette** [comment]
@smiths could you approve too? The changes you requested have been done.

**Review by smiths — APPROVED** [review]

**Comment by JacquesCarette** [comment]
There's something quite satisfying about pushing that 'merge' button, isn't there?

**Comment by smiths** [comment]
Yes!

**Comment by cd155** [comment]
Is it a routine to delete the branch once a pull request is completed?

**Comment by smiths** [comment]
Yes, we usually delete branches after the feature is merged because otherwise we end up with multiple branches in the future and we don't know which ones have useful code in them.  I restored the branch, in case you still need it for something.  If you don't need it, we should delete it again.

**Comment by cd155** [comment]
No problem, thanks for the explanation. I will delete the brach.

For the next time, I think I should name the branch in a more meaningful name.

**Comment by smiths** [comment]
Yes, meaningful names for branches are helpful.  You also want to keep your branch to one feature to resolve one issue, whenever possible.  I'll make an effort to ask next time before deleting the branch.  :smile:

**Pull request merged**
