### PR TITLE
Replace SHELL = `/bin/bash` in the Makefile with just `bash`, and add shebangs to `/usr/bin/env bash` to each script

### PR DESCRIPTION
**Pull request by balacij**
Contributes to #2642 

+ Order CI steps the same in Build.yaml and Test.yaml

@Ant13731 Do you still develop using Git Bash? If so, do you mind testing the scripts to validate that they work using Git Bash? I want to double check that Git Bash is still setting up `/usr/bin/env`.

### CODE REVIEW

**Comment by Ant13731** [comment]
Ahh, none of the makefile targets work. I get this error:
```
$ make
rm -rf "./logs/"
/usr/bin/sh: C:/Program: No such file or directory
make: *** [Makefile:146: check_stack] Error 127
```

**Comment by balacij** [comment]
I'll need to recreate it locally then and figure out what's going on. Thank you for testing it!

**Comment by balacij** [comment]
I'll re-test this on a fresh Windows setup when I can. I think it will be fine, but it's better to double check.

**Comment by Ant13731** [comment]
I did a quick check to see if `make`, `make tex`, `make analysis`, and `make graphs` would run and it worked without any problems.

**Comment by balacij** [comment]
Ah, thank you very much @Ant13731!

**Review by JacquesCarette — APPROVED** [review]

**Pull request merged**
