### PR TITLE
Empty List Constructors

### PR DESCRIPTION
**Pull request by samm82**
In addition to our current work on adding attributes, I've also created the empty list smart constructors in this branch. We haven't removed `ConVar` yet, so could this branch be re-opened if you think that merging it is a good idea? @JacquesCarette

### CODE REVIEW

**Comment by samm82** [comment]
@JacquesCarette Yeah - the problem is with `ConVar`, since it doesn't have `Attributes`. Should I go ahead and unify `ConVar` and `DQD`?

**Comment by JacquesCarette** [comment]
Not quite. Can you instead tell me exactly what the consequences of that unification would have?

**Comment by samm82** [comment]
See my latest comment on #524

**Comment by niazim3** [comment]
@JacquesCarette Would it be considered to be better if the base branch for the `remove-convar` (purple) branch was changed to be `adding-attributes`(blue) (instead of `master`) since that was where this branch branched from?
image
 
Would changing the base branch be a bad idea this far ahead into it?
image

**Comment by JacquesCarette** [comment]
I honestly don't know. It certainly isn't a bad idea. But I just don't know the full consequences this might have. And I don't know if we could easily back out such a change.

At this point, it might be safer to go via a merge rather than a rebase.

**Pull request closed without merging**
