### PR TITLE
Automate ODEInfo in a single ODE

### LINKED ISSUE #2973: ODE equation transform, how to deal with transform
In order to solve a high order of ODE, it has to transform into a system of first-order odes. To take a second-order ODE as an example

The equation `2y′′−5y′+y=0`
will be transfer to (we introduce two variable **x1 = y**  and **x2 = y'**)
- x1'=x2
- x2'=−1/2 * x1 + 5/2 * x2

For a 2nd order ODE, we can write it as a system of first-order ODEs in **two** equations
For a 3rd order ODE, we can write it as a system of first-order ODEs in **three** equations
For a 4th order ODE, we can write it as a system of first-order ODEs in **four** equations
.... and so on

In the new system of first-order ODEs, on the left-hand side are the first-order derivatives of newly introduced variables. Take `2y′′−5y′+y=0` as an example. It was re-written and become 
- x1'=x2
- x2'=−1/2 * x1 + 5/2 * x2
The left-hand side becomes x1' and x2'.

This rewriting is sufficient to allow the external libraries (scipy python) to solve a high-order ODE. The question comes what is the user input, and how to convert the user input into a well-form format which external libraries can solve.

**I am not quite sure whether Drsail is capable of this kind of transformation**. Once the input is given, Drasil has to do some internal transformation to generate the expression of the new system of first-order odes.

A temporary solution would be manually doing the transformation in `ODEInfo`. By manually creating the well-form format, the external libraries can solve the high-order ODE. However, we are currently working on getting rid of `ODEInfo`, so automating the transformation seems inevitable.

### PR DESCRIPTION
**Pull request by cd155**
For a single ODE, this PR will automate generating the `ODEInfo` part. A user can put a single ODE, and no longer manually build the `ODEInfo`.

Close #2973

This PR is partly complete #2194, because it only automates a single ODE, not a system ODE.

This PR was blocked by #2985, the `neg` need to be fixed to generate the right equation.

### CODE REVIEW

**Review by JacquesCarette — APPROVED** [review]
Very nice - all the added documentation is wonderful.

**Comment by JacquesCarette** [comment]
Before I merge this: the changes to the code are correct, right? That's a pretty big change to the equations, I want to make sure it's correct before doing this.

**Comment by smiths** [comment]
This commit really does highlight that we eventually need test cases for our generated code.  We would be more comfortable with a change like this if we could rerun our regression tests on the case studies.  I did check a few at random and the new equations appeared equal to the old equations.  A more systematic review would be a good idea though.

**Comment by cd155** [comment]
@JacquesCarette @smiths before we merge it, the code is correct if #2985 is fixed. Currently, the neg didn't add parenthesis for an `Expr`. The equation can be wrong if we have an `Expr` a + b, then neg (a + b), it will be just - a + b, which is wrong. I test a temporary fix by changing language renderers (it adds parenthesis), and all equations are right. That's why I comment this PR is blocked by #2985.

**Comment by JacquesCarette** [comment]
The way to indicate that a PR is not ready to be merged is to make it a Draft (I've just done that now).

**Comment by cd155** [comment]
Close #2985

[40feca4](https://github.com/JacquesCarette/Drasil/pull/2995/commits/40feca404b998062529db1a4af19f7495f5f14d9) fixed the bug in #2985

**Pull request merged**
