### PR TITLE
Updated answer to question 7 of the Contributor Test

### PR DESCRIPTION
**Pull request by B-rando1**
Updated answer to question 7 of the [Contributor Test](https://github.com/JacquesCarette/Drasil/blob/master/doc/Contributor's%20Test) to reflect that Travis is no longer used for CI.

I also uncommented a line at the bottom of ContributorTestAnswers.tex, so now when running `pdflatex ContributorTestAnswers.tex`, it asks if you would like to show or hide answers in the pdf.

Closes Issue #3720.

### CODE REVIEW

**Review by smiths — APPROVED** [review]
Thank you @B-rando1.  Good job with the changes, and with following the PR process.

**Comment by smiths** [comment]
I normally leave PRs for @JacquesCarette to merge, but this one is straightforward.  :smile:

**Comment by balacij** [comment]
Hmm, I'm surprised "Closes Issue #X" isn't an accepted format to automatically link issues to PRs.

("Closes #X" is what we normally use.)

**Comment by B-rando1** [comment]
Oh, good to know @balacij.  I was following the format from [Git2Know for Drasil](https://github.com/JacquesCarette/Drasil/wiki/Git2Know-for-Drasil#pull-requests), should I update it there?

**Comment by smiths** [comment]
Yes, @B-rando1, please update the Git2Know documentation to say "Closes #X"  The [documentation](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue) for automatically closing an issue doesn't mention "Closes issue #X".  

Updating Git2Know will involve editing the Wiki.

**Pull request merged**
