### PR TITLE
Switch from `tabu` to `tabularray` and upgrade Ubuntu on CI

### LINKED ISSUE #3457: LaTeX `tabu` package is broken and no longer maintained
Spun off of #3392.

When we run `make projectile_tex`, for example, we get errors in the form of
```
! Dimension too large.
\LT@max@sel #1#2->{\ifdim #2=\wd \tw@ 
                                      #1\else \number \c@LT@chunks \fi }{\th...
l.142 \end{longtabu}
                  
I can't work with sizes bigger than about 19 feet.
Continue and I'll use the largest value I can.
```

In the generated PDF this manifests in tables such as the table of symbols extending off the page to the right.

More details and discussion in #3392.

### LINKED ISSUE #3463: LaTeX out of date on CI
PR #3460 is failing CI and I think the issue is that the LaTeX on the CI is out of date.

#3460 switches from the `tabu` package to the `tabularray` package. But `tabularray` was first released in 2021 so the CI running Ubuntu 20.04 LTS (released in April 2020) does not have it. The package `texlive-latex-extra` [on Ubuntu 22.04 LTS](https://packages.ubuntu.com/jammy/all/texlive-latex-extra/filelist) contains `tabularray` whereas [on Ubuntu 20.04 LTS](https://packages.ubuntu.com/focal/all/texlive-latex-extra/filelist) it does not.

### PR DESCRIPTION
**Pull request by hrzhuang**
Closes #3457, closes #3463.

These two issues need to be closed in tandem since fixing either one without the other causes CI to fail (see also #3464).

As part of the review, it would be great if everyone could try to generate the PDFs and verify that the tables (such as the table of symbols) extending off the page to the right are fixed. The fix works on my machine, but as we have seen different LaTeX installations can produce different output.

### CODE REVIEW

**Comment by smiths** [comment]
@hrzhuang I couldn't compile with my old version of texlive (2021 version); therefore, I upgraded to 2023.  Now I get all the `\\ midrule \\` errors that I was able to avoid in the past.  😒  Of course it is better to be using the more up to date version of texlive.  The good news is that I could build all the examples and the table of symbols looks correct.  I noticed that the `toprule`, `\midrule` and `bottomrule` could be removed for `longtblr`.  The new table looks the same as the old one, as far as I can tell.  The new package is a definite improvement.

I wonder if we should add a note to the `Makefile` in the `/SRS/PDF` to tell users the expected version of texlive?  I don't think our files will compile with older versions (as shown by #3464).  It would be nice to capture this information for future users.

**Comment by hrzhuang** [comment]
The `\\ \midrule \\` error is being resolved separately (see #3458).

I agree that we should document the version of TeX Live that we are currently targeting, since as we have seen a lot can change across versions.

**Comment by smiths** [comment]
@hrzhuang, could you please create a separate issue about documenting the version of Tex Live?  We can discuss in the issue the best place to document this information.  We currently have some version information in our generated README files.  We might be able to handle this information in the same way.  We don't want the version documentation information to hold up this PR though.

**Comment by hrzhuang** [comment]
The CI is still failing. I think this is due to the `\\ \midrule \\` errors that surface after upgrading to Ubuntu 22.04 LTS. Once #3462 is merged into `master`, we can merge `master` into this branch and see if CI passes then.

**Comment by JacquesCarette** [comment]
#3462 now merged - please merge `master` into here.

**Comment by hrzhuang** [comment]
Done! CI is passing now 😃

**Comment by samm82** [comment]
In trying to run `make tex`, I keep getting the error shown below. Is this an issue with my installation? Has anyone else experienced this issue? I reinstalled `stack` and `cabal` to no avail.

<details>
  <summary>The error I'm getting (click me!)</summary>

```
$ make tex
stack install dotgen graphmod
graphmod> configure
graphmod> Configuring graphmod-1.4.4...
graphmod> build
graphmod> Preprocessing executable 'graphmod' for graphmod-1.4.4..
graphmod> Building executable 'graphmod' for graphmod-1.4.4..
graphmod> [1 of 5] Compiling Paths_graphmod
graphmod> [2 of 5] Compiling Trie
graphmod> [3 of 5] Compiling Utils
graphmod> [4 of 5] Compiling CabalSupport
graphmod> 
graphmod> src\CabalSupport.hs:68:37: error:
graphmod>     * Couldn't match type: Distribution.Utils.Path.SymbolicPath
graphmod>                              Distribution.Utils.Path.PackageDir
graphmod>                              Distribution.Utils.Path.SourceDir
graphmod>                      with: [Char]
graphmod>       Expected: [FilePath]
graphmod>         Actual: [Distribution.Utils.Path.SymbolicPath
graphmod>                    Distribution.Utils.Path.PackageDir
graphmod>                    Distribution.Utils.Path.SourceDir]
graphmod>     * In the `unitPaths' field of a record
graphmod>       In the expression:
graphmod>         Unit
graphmod>           {unitName = UnitLibrary,
graphmod>            unitPaths = hsSourceDirs (libBuildInfo lib),
graphmod>            unitModules = map toMod (exposedModules lib), unitFiles = []}
graphmod>       In an equation for `libUnit':
graphmod>           libUnit lib
graphmod>             = Unit
graphmod>                 {unitName = UnitLibrary,
graphmod>                  unitPaths = hsSourceDirs (libBuildInfo lib),
graphmod>                  unitModules = map toMod (exposedModules lib), unitFiles = []}
graphmod>    |
graphmod> 68 |                    , unitPaths    = hsSourceDirs (libBuildInfo lib)
graphmod>    |                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
graphmod> 
graphmod> src\CabalSupport.hs:76:36: error:
graphmod>     * Couldn't match type: Distribution.Utils.Path.SymbolicPath
graphmod>                              Distribution.Utils.Path.PackageDir
graphmod>                              Distribution.Utils.Path.SourceDir
graphmod>                      with: [Char]
graphmod>       Expected: [FilePath]
graphmod>         Actual: [Distribution.Utils.Path.SymbolicPath
graphmod>                    Distribution.Utils.Path.PackageDir
graphmod>                    Distribution.Utils.Path.SourceDir]
graphmod>     * In the `unitPaths' field of a record
graphmod>       In the expression:
graphmod>         Unit
graphmod>           {unitName = UnitExecutable (pretty $ exeName exe),
graphmod>            unitPaths = hsSourceDirs (buildInfo exe), unitModules = [],
graphmod>            unitFiles = case hsSourceDirs (buildInfo exe) of
graphmod>                          [] -> [modulePath exe]
graphmod>                          ds -> [d </> modulePath exe | d <- ds]}
graphmod>       In an equation for `exeUnit':
graphmod>           exeUnit exe
graphmod>             = Unit
graphmod>                 {unitName = UnitExecutable (pretty $ exeName exe),
graphmod>                  unitPaths = hsSourceDirs (buildInfo exe), unitModules = [],
graphmod>                  unitFiles = case hsSourceDirs (buildInfo exe) of
graphmod>                                [] -> [...]
graphmod>                                ds -> [d </> modulePath exe | d <- ds]}
graphmod>    |
graphmod> 76 |                    , unitPaths   = hsSourceDirs (buildInfo exe)
graphmod>    |                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
graphmod> 
graphmod> src\CabalSupport.hs:80:46: error:
graphmod>     * Couldn't match expected type: [Char]
graphmod>                   with actual type: Distribution.Utils.Path.SymbolicPath
graphmod>                                       Distribution.Utils.Path.PackageDir
graphmod>                                       Distribution.Utils.Path.SourceDir
graphmod>     * In the first argument of `(</>)', namely `d'
graphmod>       In the expression: d </> modulePath exe
graphmod>       In the expression: [d </> modulePath exe | d <- ds]
graphmod>    |
graphmod> 80 |                                      ds -> [ d </> modulePath exe | d <- ds ]
graphmod>    |                                              ^

Error: [S-7282]
       Stack failed to execute the build plan.

       While executing the build plan, Stack encountered the error:

       [S-7011]
       While building package graphmod-1.4.4 (scroll up to its section to see the error) using:
       C:\sr\setup-exe-cache\x86_64-windows\Cabal-simple_9p6GVs8J_3.6.3.0_ghc-9.2.7.exe --verbose=1 --builddir=.stack-work\dist\8a54c84f build --ghc-options " -fdiagnostics-color=always"
       Process exited with code: ExitFailure 1 
make: *** [Makefile:198: graphmod] Error 1
```
</details>

**Comment by hrzhuang** [comment]
That looks like a Stack issue? I was able to run `make tex` on both my MacBook (ARM) and a Ubuntu virtual machine (22.04 LTS, ARM). The GitHub CI running Ubuntu 22.04 LTS also passed.

Though one thing I noticed on my Ubuntu virtual machine is that the `haskell-stack` package distributed by Ubuntu runs into errors, but if I install stack using the instructions in our [New Workspace Setup](https://github.com/JacquesCarette/Drasil/wiki/New-Workspace-Setup) then it works (`curl -sSL https://get.haskellstack.org/ | sh`).

I leave it to those more experienced with Haskell and Stack to comment further.

**Comment by JacquesCarette** [comment]
(Since it works on CI, I'm merging now - the other problems can be split into a new issue)

**Pull request merged**
