### PR TITLE
Test for adding datatable to website

### PR DESCRIPTION
**Pull request by Ant13731**
I got this error when I tried to run this locally (using `make` in `.\code\website`):
```
 website.EXE: DEPLOY_FOLDER: getEnv: does not exist (no environment variable)
make: *** [Makefile:7: run] Error 1
```
So I wanted to see if the automated tests would work. I'm not really how to generate the website to see if it worked locally.

Contributes (maybe closes?) #2221 #2231

### CODE REVIEW

**Comment by Ant13731** [comment]
After trying to run make deploy, I found that I had to install graphviz first.

**Comment by balacij** [comment]
The CI for the website only runs in the full `Build.yaml` script (not the mini `Test.yaml` variant) which only runs on the `master` branch. So, it shouldn't run here.

I think the `deploy_lite` target is what you'd be interested in with this? https://github.com/JacquesCarette/Drasil/blob/b36114f5355ff8b0a290622c6097d9068f13a571/code/Makefile#L212-L216

I previously had a small script to help me with mock deployments locally. I ran through the full steps in the Test.yaml CI, and then used it:

https://github.com/JacquesCarette/Drasil/blob/151e6638fea05bf25d57cb84a06c3e55c302fe9a/code/rn.sh

You'd just need to run `sh rn.sh` in the `code` folder, with that file placed in the `code` folder.

**Comment by Ant13731** [comment]
Okay thanks! I'll give it a try.

**Comment by Ant13731** [comment]
I'm currently going through the process listed in the Test.yaml section, but before I did, I tried the script and it gave this: 
```
Only perform deploys for master (attempted on: master).
Skipping.
```
Does it only run on master? Do I need to fork the repo and try it on the master of the forked one?
I'll try it again once make deploy finishes (its taking some time to compile) but I'm hoping the website will work after its done anyways.

**Comment by balacij** [comment]
Ah, if you're using the `rn.sh` script I made, you'll need to update the `GITHUB_REF=master` to `refs/heads/master`. It might be good to also update that error message.

Sorry about that! I forgot that I updated it since that script's original version.

**Comment by Ant13731** [comment]
Ah okay thanks!

**Comment by Ant13731** [comment]
I tried the new script and it works but now I'm getting a lot of different errors (mostly from the deploy_wrapper.sh file.

My git bash says that `rev` command not found - I think the git bash shell that I'm using on Windows doesn't have it so I might have to try something else. 

Next, I've gotten a bunch of `cannot stat: No such file or directory` for all of the object oriented language html files. 

For some doxygen files, I get the following:
```
doxygen doxConfig
process_begin: CreateProcess(NULL, doxygen doxConfig, ...) failed.
make (e=2): The system cannot find the file specified.
make[1]: *** [Makefile:22: doc] Error 2
```

It did generate an index.html file in the deploy folder, but my additions aren't generating there.

**Comment by balacij** [comment]
Yep, for the `cannot stat` errors, we have a ticket going for it: https://github.com/JacquesCarette/Drasil/issues/2524 

Hmm, `rev` is just a tool that reverses the characters in inputted text.

Perhaps you can install BusyBox for some minimal tools that are on Linux? I'm not too sure what the norm is for development on Windows. https://busybox.net/

**Comment by Ant13731** [comment]
Thanks! I did some looking around and I found that the cygwin shell has make so I can try it there.

**Comment by Ant13731** [comment]
@balacij I just finished installing the windows subsystem for linux so I'm getting all the tests ready to go. I was looking at the `rn.sh` script again and I was just wondering what the GITHUB_SHA represents and if the GITHUB_REPOSITORY variable should be JacquesCarette/Drasil instead? Thanks for all your help!

**Comment by balacij** [comment]
@Ant13731 The `GITHUB_SHA` is meant to be the latest commit hash on the branch and the `GITHUB_REPOSITORY` is meant to be the related GitHub repository location. They're dynamically set as environment variables by the Github Actions runner, check [their docs](https://docs.github.com/en/actions/reference/environment-variables#default-environment-variables) if you'd like to know more about it. So, you don't need to worry about what values you give them, because they'll always be the "correct" data when running on GitHub Actions.

Note that the script is only meant to help with replicating the environment variables that GitHub Actions automatically creates for each CI run.

**Comment by Ant13731** [comment]
I'm really close to getting it to work fully! Running the build steps in order almost works perfectly, except the analysis folder doesn't generate automatically (I have to run `make analysis` before it works). Also, when I click the link for the data table, it just downloads the csv file. Is this okay?

**Comment by balacij** [comment]
You'd need to ask about whether just a download or a link to the GitHub tree is okay to @JacquesCarette. I'm not quite sure what's desired.

Yep, you'll probably need to add that as a step in the CI. Would you need to add it to the Test.yaml as well? I imagine we would want it there too, but I'm not sure what the analysis is for.

Hmm, that's an interesting issue. Let's try this:
1. In your Windows version of Stack, run `stack --numeric-version` and make note of the version
2. In your WSL, run `stack upgrade --binary-version <version>` where `<version>` is the version from ^.

**Comment by Ant13731** [comment]
Okay thanks. My linux one was using 2.7.1 while my windows is on 2.5.1, so I changed my linux one back to 2.5.1 and it seems to work now.

**Comment by Ant13731** [comment]
I looked into making the data table visible on the website and I found this [link that uses php to convert a csv file into an html table](https://stackoverflow.com/questions/518795/dynamically-display-a-csv-file-as-an-html-table-on-a-web-page). I don't really know any php (or how it fits in with html files), but I think this might be able to help display the file on the website.

**Comment by balacij** [comment]
Nice! You could probably do this with Python too if that's easier (Python comes with really really nice tooling for CSVs).

Though, if you'd prefer to do it via Haskell, there is [`Cassava`](https://www.stackage.org/lts-16.31/package/cassava-0.5.2.0) which we can use. I'm not too sure how many dependencies it would be adding to the website package, but it's probably worth investigating. It can then be used in the website package in the template for `index.html`.

**Comment by Ant13731** [comment]
Do you think it would be good if there was a python file in the scripts folder that could create a new `database.html` file, and then we could link that to the main website? I'm guessing there's a way to call python files to run within a bash script. Python seems to look a lot easier than haskell in terms of parsing csv files (especially since this one is pretty big). I think it might also be worth looking into colouring some of the cells of an html table to easily view the data types and places they are defined.

**Comment by balacij** [comment]
There's a couple of ways we could do this.

If we're okay with using a [DataTables](https://datatables.net/) table to display the data, the sizing wont be an issue, and the scripting will be rather straightforward. With this way, we'd only need to upload the csv file to some location we know. Then, with Javascript in the web browser, we can load that csv file into the DataTable. With this way, we'd have very little programming to do really. If you want to add colouring too, Javascript + DataTables will make this near trivial -- there's a "loading data event" that we can hook into to set colour of cell based on value of cell. I think adding DataTables would be good regardless of where we gather the data from. It allows us to have cool features like sorting, searching, paging, etc. It also follows the theme of #2300.

The Python way or the Haskell way will have about the same difficulty. The Haskell way is certainly easier if you want to have our Home/`index.html` page contain the actual table itself.

There is also another way with Haskell. We could edit the actual `DataTableGen.hs` file to output an html file alongside the csv. This would likely be a good solution too. I think you'd just want to play around with this function:
https://github.com/JacquesCarette/Drasil/blob/b470ff3dac52dc433a027570793cdef94de7d888/code/scripts/DataTableGen.hs#L116-L126

I think this way would also result in little programming.

**Comment by Ant13731** [comment]
Okay, sounds good. I tried to make something with python and it's not really working so I'll try modifying the existing haskell file now

**Comment by JacquesCarette** [comment]
Excellent discussion.  Modifying the Haskell generator to output html as well as csv seems like the best solution.  The point of the csv is that Excel really is a decent tool for trying to look more deeply into the data. For more cursory investigation, some kind of html-based table seems like a good idea. Strictly speaking, we don't need the csv on the web site; but I like being fully open, and it doesn't hurt to have it there too, so why not?

**Comment by Ant13731** [comment]
I think this should be just about ready to implement, so I'll fix any mistakes from the auto tests and mark it as ready for review. Thanks for all your help @balacij!

**Review by JacquesCarette — APPROVED** [review]

**Pull request merged**
