### PR TITLE
lining up Cls in PDcontroller  (Closes Issue #2343)

### PR DESCRIPTION
**Pull request by Awurama-N**
closes issue #2343
lined up the code in PDcontroller. what was previously lines 19-32.

### CODE REVIEW

**Review by JacquesCarette — CHANGES_REQUESTED** [review]
By "lined up", I meant that all the `=` signs should be in the same column, and that all the `(pn`... arguments too, then the strings, then the last `[]` argument.  You'll need to use spaces to do that, like the example that I linked to.

The code should end up looking like a table.

**Comment by Awurama-N** [comment]
Okay thank you, i moved over the = and the (pn but i wasn't sure about the strings & bracket, because i thought it'd get too long. I'll add that now

**Comment by Awurama-N** [comment]
This is what the code looks like to me now, i tried to create a commit to push but it says no changes were made.

Screenshot 2021-05-05 at 8 34 03 PM

**Comment by Awurama-N** [comment]
Screenshot 2021-05-05 at 8 36 45 PM

**Comment by JacquesCarette** [comment]
Right, that code looks perfect. I'll investigate a bit.

**Comment by Awurama-N** [comment]
okay thank you

**Comment by JacquesCarette** [comment]
So the file that is in the repo, in your branch, is not lined up. My guess is that your editor is "too smart" and removes all those spaces before saving!  Whatever editor you're using, you'll need to investigate your settings, and turn off this option.

**Comment by Awurama-N** [comment]
Oh okay okay, I will sort that out

**Comment by smiths** [comment]
@Awurama-N, are you sure that you changed the right branch?  It looks like you checked out the branch, but didn't make any changes to it.   Maybe you edited another branch, maybe master?, by mistake?

**Comment by Awurama-N** [comment]
hmm, how can i be sure i'm working in the right branch?
 is there code i should input after `git checkout`?

**Comment by JacquesCarette** [comment]
You did commit some code to branch `issueSolution`, and pushed it, as I was able to pull it down. It was changed, in that the extra returns and blank lines were gone.  So you did those edits in the right branch, in the right way.

What seems to have disappeared are the extra spaces on those lines.

**Comment by Awurama-N** [comment]
Oh okay then it is probably the settings of the editor ignoring the spaces. I'm going to try to turn that off.

**Comment by JacquesCarette** [comment]
You should not be checking in your private vscode settings into the repo itself. Only the changes to the Haskell files please.

**Comment by JacquesCarette** [comment]
Yes, that worked!  Now you just have to remove `settings.json` from this commit, and it will be good to go.

**Review by JacquesCarette — APPROVED** [review]

**Pull request merged**
