### PR TITLE
PR - Hlint camelCase fixes

### PR DESCRIPTION
**Pull request by danscime**
Removing underscores in favour of camelCase for naming as per #1249.

### CODE REVIEW

**Comment by danscime** [comment]
Working on merging conflicts.

**Comment by danscime** [comment]
Fixed merge. Builds on local machine.

**Comment by JacquesCarette** [comment]
Sorry, merge of previous stuff caused a conflict.

**Comment by danscime** [comment]
Fixed.

**Comment by JacquesCarette** [comment]
and again...

**Comment by danscime** [comment]
Fixed

**Comment by JacquesCarette** [comment]
Tried to do a hand-merge with the web interface... let's see if I managed to do it properly!

**Comment by JacquesCarette** [comment]
So the problem now is as follows (from the log file):
```
diff -r -X ../.gitignore -x '*.txt' stable/nopcm/src/cpp/InputParameters.cpp build/NoPCM/src/cpp/InputParameters.cpp
37c37
<     if (!(((rho_W_min < inParams.rho_W) && (inParams.rho_W <= rho_W_max)))) {
---
>     if (!(((ρ_W_min < inParams.rho_W) && (inParams.rho_W <= ρ_W_max)))) {
```
stable is indeed correct. And, as far as I can tell, the SWHS (which is where these are defined) does it right. So I have no idea at all what's causing the output to have unicode -- @bmaclach this is likely related to some of the changes you did (and that I merged in from master).

**Comment by bmaclach** [comment]
@JacquesCarette Yes, it was related. We need to use `mkQuantDef'` to conserve the stage-dependent symbol. `mkQuantDef` uses only the `Equational` stage symbol. Thinking about this again, though, and in light of the trouble it's caused, I don't see why we would ever want to "overwrite" our stage dependent symbol like `mkQuantDef` does. I'm thinking we can probably just remove `mkQuantDef` and rename `mkQuantDef'` as `mkQuantDef`... I pushed a fix given what we have currently but if you agree with this proposed change let me know and I can do it (in a separate PR probably?)

**Comment by JacquesCarette** [comment]
I agree - no idea what we were thinking with `mkQuantDef` !! And yes, separate PR please.

**Comment by JacquesCarette** [comment]
Sigh. And the build is failing because of hlint parsing problems?!? Any idea? Maybe @Mornix knows?

**Comment by bmaclach** [comment]
The errors seem related to my GOOL changes, which is weird because the build passed for that branch. And  I get no errors when running hlint locally, plus the code it's complaining about looks fine to me. So hopefully @Mornix knows!

**Comment by Mornix** [comment]
Took a quick look. Looks like HLint pushed a new version ~4hours before this build was run. The way HLint is configured into the CI we use whatever the latest version is when running, One of the in-progress changes is switching Haskell parsing libraries from HSE to ghc-lib-parser. Looking into why exactly it's marking things as parse error's however I'm guessing it has something to do with `static` as that is present on every line marked.

**Comment by Mornix** [comment]
Did a quick test, HLint is indeed failing on `static`. I'm assuming with the switch they're treating all extensions as "loaded" and thus [static pointers](http://downloads.haskell.org/~ghc/8.2.2/docs/html/users_guide/glasgow_exts.html#static-pointers) are in play and it's recognizing `static` (incorrectly) as part of the language extension.

**Comment by JacquesCarette** [comment]
In this meantime, it might be a good idea to rename `static` to something else? @danscime can you take care of that?

**Pull request merged**
