### PR TITLE
MIS Generation

### LINKED ISSUE #1363: File Structure of MIS/SRS in Examples
Right now, the SRS and MIS are being "encoded" in Body.hs, which makes the code more difficult to deal with. Can this be split into SRS.hs and MIS.hs for better information hiding, or should it stay as Body.hs?

### PR DESCRIPTION
**Pull request by samm82**
This includes the work done last summer on automating the MIS generation for GlassBR - changes will be made in separate PRs in the GlassBR MIS Project.

Closes #1363

### CODE REVIEW

**Comment by samm82** [comment]
Closed until #1363

**Comment by samm82** [comment]
Closed until discussion as mentioned in #1366

**Comment by JacquesCarette** [comment]
There seems to be a loop here, where here you close it until the discussion is resolved, and in the discussion you say it'll be easier when this is merged...

**Comment by samm82** [comment]
Yeah I'm just keeping it closed until we actually figure out what we want from the MIS. I started this while trying to salvage our work from last summer, and I didn't do a lot with the MIS generation, so I'm still trying to figure out what @niazim3 and @elwazana did. A discussion before proceeding sounds like the best plan and is what I should have done from the start.

**Pull request closed without merging**
