### PR TITLE
[Small PR] Capitalization Fix for SSP Program Name

### PR DESCRIPTION
**Pull request by samm82**
Changed "Slope Stability analysis Program" to "Slope Stability Analysis Program"

### CODE REVIEW

**Comment by bmaclach** [comment]
This capitalization was intentional because "analysis" was not part of the acronym "SSP". I believe @smiths was the one who originally asked that I make "analysis" lowercase.

**Comment by samm82** [comment]
I'll wait for @smiths, but I guess the PR can be closed then.

**Comment by JacquesCarette** [comment]
I'll close it now, as I'm fairly sure I know what @smiths will say.

**Comment by smiths** [comment]
@JacquesCarette, you are correct about what I would say.  😄

**Pull request closed without merging**
