### PR TITLE
Converting GlassBR's lrIsSafe IMod into an EquationalModel

### PR DESCRIPTION
**Pull request by Awurama-N**
closes Issue #2565

### CODE REVIEW

**Comment by balacij** [comment]
Nice! One less `relToQD` :smile:

**Comment by Awurama-N** [comment]
@balacij there is no `relToQD` in Body.hs now, or did you mean i took one out that i wasn't suppose to? (and should put it back)

**Review by JacquesCarette — APPROVED** [review]

**Comment by balacij** [comment]
Ah, I meant that it's good that it's gone now. I'm sure @JacquesCarette will be happy about that.

**Comment by JacquesCarette** [comment]
Indeed.

**Pull request merged**
