### PR TITLE
3410 Reuse Organization of Document section between examples

### LINKED ISSUE #3410: Reuse Organization of Document Section between examples
Since we are adding SmithAndKoothoor2016 and SmithEtAl2007 to all the places where SmithAndLai2005 was mentioned, can the sentence: 

image

be used instead of the current sentence: 

image

for all the examples that have the section for the Organization of Document?

This issue is related to #3318 and this discussion [here](https://github.com/JacquesCarette/Drasil/pull/3407#discussion_r1190326905).
@smiths @samm82

### PR DESCRIPTION
**Pull request by harmanpreet-sagar**
Closes #3410: Reuse the Organization of Document section between examples. Changes made to `examples`, `drasil-docLang` and `stable`.

### CODE REVIEW

**Review by smiths — CHANGES_REQUESTED** [review]
@harmanpreet-sagar, please remove the text ", with some aspects taken from Volere template 16 \cite{rbrtsn2012}" from all the examples. Although this is technically true, the information on the Volere template is included in the SmithEtAl references.  It is cleaner if we don't mention it here.  (If we mention the Volere template, then we should mention all the templates that the SmithEtAl template is based on, and then we are adding too much detailed text to all our examples.)

**Comment by harmanpreet-sagar** [comment]
Ok, I will make that change right now!

**Review by smiths — APPROVED** [review]
The changes to stable look good to me.

**Review by smiths — APPROVED** [review]
The changes to stable look good to me.

**Review by smiths — APPROVED** [review]
The changes to stable look good to me.

**Review by JacquesCarette — APPROVED** [review]
Love these kinds of PRs - shortens the code, makes things more consistent.

**Pull request merged**
