### PR TITLE
SSP System Context

### PR DESCRIPTION
**Pull request by bmaclach**
This updates the System Context section of the SSP SRS to match stable.

### CODE REVIEW

**Comment by JacquesCarette** [comment]
Fine to me as well, but now there is a conflict, so master needs to be re-merged in, please.

**Comment by bmaclach** [comment]
Master re-merged, though I fear we are going to get another conflict with import lists between this and #1144. These import lists are really messing with my supposedly independent pull requests, but I'm not sure if there's anything that we can do about it without combining PRs.

**Comment by JacquesCarette** [comment]
Yes, you're right, this needs re-merged now that #1144 is done.

**Comment by bmaclach** [comment]
Master re-merged.

**Pull request merged**
