### PR TITLE
Change 'const' to 'constant' in gool

### PR DESCRIPTION
**Pull request by ManvendraJani**
closed issue #2970

### CODE REVIEW

**Comment by JacquesCarette** [comment]
Why did you close this?

**Comment by ManvendraJani** [comment]
> Why did you close this?

There was an error with one of the checks. I mentioned it in #2970

**Comment by smiths** [comment]
@JacquesCarette or @balacij can correct me if I'm wrong, but another approach @ManvendraJani besides closing a PR with a merge error is to relabel it to include WIP (Work in Progress) in the title.  When the error is correct you can remove the WIP and request a review of the PR.

**Comment by balacij** [comment]
Using GitHub's PR 'drafts' feature might be a tad easier, but that is normal and often used too, @smiths.

@ManvendraJani #2904 is an example of a draft PR -- it's not mergeable until the author explicitly marks it as 'ready for review'.

**Comment by smiths** [comment]
Oh, I like this draft PR idea.  Let's do it that way!

**Comment by ManvendraJani** [comment]
Will keep this in mind moving forward, thanks!

**Comment by JacquesCarette** [comment]
So this one should be re-opened and further worked on?

**Comment by smiths** [comment]
@ManvendraJani I know you used the WIP label, but I couldn't resist clicking on the convert to Draft option suggested by @balacij.  :smile:

**Review by bmaclach — CHANGES_REQUESTED** [review]
The changes to drasil-gool look good to me (admittedly I haven't looked at this in years, and had forgotten too much, but I spent the last hour or so beginning to refresh my memory on this, so I can review this somewhat meaningfully).

What seemed odd to me was that you wouldn't have to update any of the Drasil code that uses GOOL. But after reacquainting myself with that part of drasil-code, it's indeed true that GOOL's `const` wasn't actually used by Drasil (yet).

The only usage of `const` I found was in the test GOOL program, `HelloWorld.hs`, and that, I think, should be updated. I'm not sure if we have any automated checks on it, but I do think that test program is valuable and should be maintained, as it uses many parts of GOOL that aren't yet used by Drasil.

**Comment by ManvendraJani** [comment]
@bmaclach I am not able to find HelloWorld.hs anywhere?

**Comment by smiths** [comment]
@ManvendraJani I found a [`HelloWorld.hs`](https://github.com/JacquesCarette/Drasil/blob/master/code/drasil-code/test/HelloWorld.hs) file using the search features of Finder on my Mac.  I'm sure there are more clever ways to do the search at the command line.  :smile:

**Comment by smiths** [comment]
Thanks for the feedback @bmaclach!  Did you get pulled in by our automatic review requests?  @samm82 has added a [code ownership file](https://github.com/JacquesCarette/Drasil/blob/master/.github/CODEOWNERS) that automates some of the review tasks.  I believe we put you down as one of the GOOL reviewers.  If there are any problems with this, please let us know.  :smile:

**Review by bmaclach — APPROVED** [review]
Looks good!

**Comment by bmaclach** [comment]
> Thanks for the feedback @bmaclach! Did you get pulled in by our automatic review requests? @samm82 has added a [code ownership file](https://github.com/JacquesCarette/Drasil/blob/master/.github/CODEOWNERS) that automates some of the review tasks. I believe we put you down as one of the GOOL reviewers. If there are any problems with this, please let us know. 😄

Yeah, I was automatically added. And it's not a problem, I checked my name on @samm82's code ownership ticket because I was interested in staying involved!

**Review by JacquesCarette — APPROVED** [review]

**Pull request merged**
