### PR TITLE
[Small PR] Made Labels more meaningful in GlassBR

### PR DESCRIPTION
**Pull request by samm82**
As per smiths/caseStudies#106, labels for T1 and T2 were changed to contain useful information.

### CODE REVIEW

**Comment by szymczdm** [comment]
@samm82 I believe some of the other PRs are causing conflicts here, can you please sort them out?

**Comment by smiths** [comment]
I mentioned in comments that the Drasil names that have t1 and t2 in them are still not great names.  The order of t1 and t2 is arbitrary.

**Comment by samm82** [comment]
Addressed in the addGlassDD6Notes branch (it was a small fix so I just tacked it on to the branch)

**Comment by smiths** [comment]
Looks good.  I still like a prefix (like T) that tells me that this is a theoretical model, but it is best that the examples all be consistent.

**Comment by samm82** [comment]
a) So do you want me to add the prefix?
b) Should I change the other examples with a similar fix?

**Comment by smiths** [comment]
Hold off for now.  It is more of a stylistic preference, and we haven't really converged on a style for Drasil code.  Eventually we may want to put something in the contributor's guide related to this, but our conventions aren't yet clear.  I think we can close this issue for now.

**Pull request merged**
