### PR TITLE
Added Time Step to SWHS

### PR DESCRIPTION
**Pull request by samm82**
As per #1307, added time step to SWHS.

_Closes #1307_

### CODE REVIEW

**Comment by samm82** [comment]
@JacquesCarette The issue with making them `ConstrConcept`s is that the list `swhsInputs` is of type `[UncertQ]`, since the Table of Input Data Constraints has an Uncertainty column. The instant fix that comes to my mind is changing `UncertQ` to have a `Maybe Uncertainty` that will display "--" if `Nothing`, but that just seems like the same hack as zero uncertainty.

**Comment by JacquesCarette** [comment]
Not all examples have uncertainties. So take a look at the other examples too. I'm guessing that at least one other involves mixed inputs, and you'll find a better solution there.

**Comment by samm82** [comment]
@JacquesCarette I've looked through the examples, and in every example with a Table of Input Data Constraints, each value has an uncertainty. Most of them are 10%, which might be placeholders.

**Comment by JacquesCarette** [comment]
Indeed - that's a problem. This is a bigger issue, and should have its own issue. And this PR will be blocked on that, as we do want to design this properly rather than just hack it in.

**Comment by samm82** [comment]
What if I set these values to the default 10% uncertainty, then I'll open up an issue with for determining what the uncertainties should actually be/how best to denote no uncertainty? This way, these values will be kept in the same way as the others (and time step won't be lost), and we can make a pass over all examples/quantities for this new issue.

**Comment by JacquesCarette** [comment]
Sounds like a good plan.

**Comment by samm82** [comment]
I'll make the issue, and this PR is now good-to-go.

**Pull request merged**
