### PR TITLE
SSP Slice Weight Derivation

### PR DESCRIPTION
**Pull request by bmaclach**
This PR adds a derivation for slice weights, in a similar style to what was done for surface/base hydrostatic forces. This includes consolidating the 3 slice weight DDs into a single GD. This contributes to #1332.

### CODE REVIEW

**Comment by bmaclach** [comment]
@smiths I am waiting for your feedback on the revised moment equilbrium deriviation before bringing it to Drasil (see #1326)

The base hydrostatic force equation in Drasil does not match Brandon's code. We had thought we found a mistake with Brandon's code where he was multiplying by ell_i (the length of the base) instead of b_i (the width of the slice), but now it seems like that's not the case and Brandon's version was right all along.

After reading your explanation and drawing it out, I mostly understand the derivation but I do have a couple questions. A quick meeting would be helpful. You seem to be booked up for the next couple of days though. Should we wait until Thursday? I'm available any day except Friday this week.

**Comment by smiths** [comment]
Yes, I have #1326 in my e-mail inbox to remind me to look over it again.  I'll get to that soon.

I just deleted what I was writing because I think you are right when you say that Brandon was right.  I 
was originally writing an explanation that the surface load is different from the base load and then I realized that they aren't different.  We can't just talk about the weight of the water from the surface slice, like I originally told you.  The water will be pushing normal to the slope surface along the length of the surface.  The weight of the water as we calculated would be parallel to the y-axis, which ignores part of the force.  Also, the weight of the water passes directly through the axis of rotation, so it doesn't actually generate any moment.  We need to consider the resultant from the load distributed along the surface.  I'm pretty sure the equation will be the same as what Brandon had before.

Although  Brandon was likely right, we are still highlighting the value of deriving the equations.  If Brandon had shown the derivation of the original equation, our task would be verifying that derivation, not deriving it ourselves.  @szymczdm, if you were planning on using the Brandon example that I previously highlighted for the calculation of the surface hydrostatic force, the point is a little more nuanced than I originally thought.  😄 

My schedule for tomorrow (Wednesday) looks to be opening up, especially in the afternoon.  If we can find a time to meet to discuss the documentation of design, you and I could meet immediately before or after that meeting.

**Comment by JacquesCarette** [comment]
(and another master merge will be needed)

**Comment by bmaclach** [comment]
Merged master.

Also discussed with @smiths and decided that, since this PR isn't introducing anything wrong, we should be able to merge this one in. I will fix the mistakes with the base/surface hydrostatic force derivations in a fresh branch.

**Comment by smiths** [comment]
@bmaclach, I'll merge this pull request.  Please fix the mistakes with the base/surface hydrostatic force derivations in a fresh branch, as we discussed.   I'll also delete the branch.

**Pull request merged**
