### PR TITLE
Fix "Loose" input structure (and NoPCM)

### PR DESCRIPTION
**Pull request by bmaclach**
This PR applies the last couple fixes to `Loose` input structure, including renaming it to `Unbundled` (and `AsClass` to `Bundled`). With these fixes, NoPCM finally compiles (😃) so I updated the Makefile to compile NoPCM as part of our build (Thanks @Mornix for the comments in the Makefile explaining how to do that. Very helpful!).

This PR depends on #1629, so that one should be merged in first.

@Mornix, I'm adding you as a reviewer for the Makefile changes I made (d1beb1c455b964933797bc41846cea2428263967). In addition to following your instructions for adding NoPCM to the build, I had to update it so that the input file for NoPCM would be copied over to the `src` folders. We already did this for GlassBR, but I tried to update the rule to be more general and automatically do it for all of the examples for which we generate code. It worked, but for some reason the order in which things get executed changed. Before, a single rule would be carried out for all examples, and then it would move on to the next rule, so something like this would print to the console:
```
cd build/Tiny && stack exec -- tiny
cd build/GlassBR && stack exec -- glassbr
test -d build/GlassBR/src/python && cp ./datafiles/GlassBR/*.txt build/GlassBR/src/python/
test -d build/GlassBR/src/java && cp ./datafiles/GlassBR/*.txt build/GlassBR/src/java/
test -d build/GlassBR/src/csharp && cp ./datafiles/GlassBR/*.txt build/GlassBR/src/csharp/
test -d build/GlassBR/src/cpp && cp ./datafiles/GlassBR/*.txt build/GlassBR/src/cpp/
cd build/NoPCM && stack exec -- nopcm
cd build/SWHS && stack exec -- swhs
cd build/SSP && stack exec -- ssp
cd build/Chipmunk && stack exec -- chipmunkdocs
cd build/Projectile && stack exec -- projectile
cd build/Template && stack exec -- template
diff -r -X ../.gitignore -x '*.txt' "stable/tiny/" build/Tiny/ > logs/Tiny_log.log 2>&1
diff -r -X ../.gitignore -x '*.txt' "stable/glassbr/" build/GlassBR/ > logs/GlassBR_log.log 2>&1
diff -r -X ../.gitignore -x '*.txt' "stable/nopcm/" build/NoPCM/ > logs/NoPCM_log.log 2>&1
diff -r -X ../.gitignore -x '*.txt' "stable/swhs/" build/SWHS/ > logs/SWHS_log.log 2>&1
diff -r -X ../.gitignore -x '*.txt' "stable/ssp/" build/SSP/ > logs/SSP_log.log 2>&1
diff -r -X ../.gitignore -x '*.txt' "stable/gamephys/" build/Chipmunk/ > logs/Chipmunk_log.log 2>&1
diff -r -X ../.gitignore -x '*.txt' "stable/projectile/" build/Projectile/ > logs/Projectile_log.log 2>&1
diff -r -X ../.gitignore -x '*.txt' "stable/template/" build/Template/ > logs/Template_log.log 2>&1
```
Now, it does that for the first two examples (GlassBR and NoPCM, the two with generated code) but then for the rest of the examples it does all of the rules for that example, and then moves on to the next example. So what prints to the console is:
```
cd build/GlassBR && stack exec -- glassbr
test -d build/GlassBR/src/python && cp ./datafiles/GlassBR/*.txt build/GlassBR/src/python/
test -d build/GlassBR/src/java && cp ./datafiles/GlassBR/*.txt build/GlassBR/src/java/
test -d build/GlassBR/src/csharp && cp ./datafiles/GlassBR/*.txt build/GlassBR/src/csharp/
test -d build/GlassBR/src/cpp && cp ./datafiles/GlassBR/*.txt build/GlassBR/src/cpp/
cd build/NoPCM && stack exec -- nopcm
test -d build/NoPCM/src/python && cp ./datafiles/NoPCM/*.txt build/NoPCM/src/python/
test -d build/NoPCM/src/java && cp ./datafiles/NoPCM/*.txt build/NoPCM/src/java/
test -d build/NoPCM/src/csharp && cp ./datafiles/NoPCM/*.txt build/NoPCM/src/csharp/
test -d build/NoPCM/src/cpp && cp ./datafiles/NoPCM/*.txt build/NoPCM/src/cpp/
diff -r -X ../.gitignore -x '*.txt' "stable/glassbr/" build/GlassBR/ > logs/GlassBR_log.log 2>&1
diff -r -X ../.gitignore -x '*.txt' "stable/nopcm/" build/NoPCM/ > logs/NoPCM_log.log 2>&1
cd build/Tiny && stack exec -- tiny
diff -r -X ../.gitignore -x '*.txt' "stable/tiny/" build/Tiny/ > logs/Tiny_log.log 2>&1
cd build/SWHS && stack exec -- swhs
diff -r -X ../.gitignore -x '*.txt' "stable/swhs/" build/SWHS/ > logs/SWHS_log.log 2>&1
cd build/SSP && stack exec -- ssp
diff -r -X ../.gitignore -x '*.txt' "stable/ssp/" build/SSP/ > logs/SSP_log.log 2>&1
cd build/Chipmunk && stack exec -- chipmunkdocs
diff -r -X ../.gitignore -x '*.txt' "stable/gamephys/" build/Chipmunk/ > logs/Chipmunk_log.log 2>&1
cd build/Projectile && stack exec -- projectile
diff -r -X ../.gitignore -x '*.txt' "stable/projectile/" build/Projectile/ > logs/Projectile_log.log 2>&1
cd build/Template && stack exec -- template
diff -r -X ../.gitignore -x '*.txt' "stable/template/" build/Template/ > logs/Template_log.log 2>&1
```
It might not even matter, but I'm just confused about why it happened.

### CODE REVIEW

**Comment by JacquesCarette** [comment]
I will wait until @Mornix and @smiths review this one. And there's a merge that needs done [I don't know why!]

**Comment by smiths** [comment]
I like these changes, but I do have a question.   I believe we have discussed this before, but it is easier to ask again than to search for the answer.  😄 This is an example where we have variabilities: `Unbundled` versus `Bundled`.  Which one goes in stable?  Should we have two versions in stable?  One for each variability?  I know we can't do this for every variability, but if I remember the previous conversation, we were going to have some representative family members in stable.

**Comment by bmaclach** [comment]
@smiths Currently we do `Bundled` for GlassBR and `Unbundled` for NoPCM. That was how it was set up prior to me starting to work on the code generator, so I'm not sure what the rationale was.

In the past when we talked about this it was in relation to Projectile. I think we should generate multiple family members when we start generating code for Projectile, but doing the same for every example might be redundant. That's my thought at least.

**Comment by smiths** [comment]
Thanks @bmaclach.  Yes, modifying our variabilities between the different case studies makes sense.  That way we don't have an explosion of different versions of stable, but we still cover our variabilities.  At some point we will likely need to add a few different variabilities for a given case study, maybe for Projectile.  We should make an effort to document this.  It is good that we have at least one example for each of Bundled and Unbundled, but it seems like that decision is documented nowhere other than in the Drasil code.  Is there a logical place that we could put a little table that has our case studies along one axis and our variabilities along another?  When needed we could add multiple versions of the case studies to cover the case where we generate one with a different set of variabilities.

**Comment by Mornix** [comment]
Looking solely at the Makefile changes, everything looks like it’s fine. My guess is the execution order change is the result of how `make` resolves build order and running `make` with a single thread.

**Comment by bmaclach** [comment]
@smiths I like the idea of documenting the choices we've made for variabilities for each example. Maybe in the README in the root directory of the repo? Or the web page? Or both?

**Comment by smiths** [comment]
> @smiths I like the idea of documenting the choices we've made for variabilities for each example. >Maybe in the README in the root directory of the repo? Or the web page? Or both?

@bmaclach, I think our README might already have too much information.  I think the case studies versus variabilities table would get lost there.  However, I like your idea of this information being on the web-page.  I think it could be incorporated into the continuous deploy version of the web-page that @danscime is working on.  The intro to the case studies could say which examples have which variabilities in a table in the html.  Can you please talk to @danscime about this.  Ideally we will eventually follow the advice of @JacquesCarette and automatically generate this table of case studies versus variabilities from the information in the case study code.  I don't think we are there yet though.

**Comment by JacquesCarette** [comment]
Yep, all sounds great!

**Comment by bmaclach** [comment]
@danscime This is where the original discussion about adding the table of design choices to the web page happened.

**Comment by smiths** [comment]
Thank you @bmaclach.  @danscime, can you please create an issue for creating the table of design choices.  It will be easier to find in the future if there is a separate issue for it.  You can link back to this discussion for traceability.

**Pull request merged**
